import type { Exercise } from "./exercises";

export const additionalCourseExercises: Exercise[] = [
  {
    slug: "introduccion-ecuacion-valor-absoluto", number: "07", course: "Introducción a las Matemáticas", courseSlug: "introduccion-matematicas", collection: "Ejercicios",
    title: "Una ecuación con dos valores absolutos", topic: "Ecuaciones y valor absoluto", difficulty: "Inicial", estimatedTime: "10 min",
    statement: ["Resuelve $|3x-2|=|2x+7|$ y comprueba todas las soluciones en la ecuación original."],
    relatedTheory: [{label: "Valor absoluto y ecuaciones cuadráticas", href: "/cursos/introduccion-matematicas#intro-ecuaciones-2"}],
    hints: ["Dos números tienen el mismo valor absoluto si son iguales o si uno es el opuesto del otro.", "Separa los casos: $3x-2=2x+7$ y $3x-2=-(2x+7)$.", "Resuelve ambas ecuaciones lineales y sustituye cada resultado dentro de los valores absolutos originales."],
    solution: [{title: "1. Interiores iguales", body: "$3x-2=2x+7$ da $x=9$."}, {title: "2. Interiores opuestos", body: "$3x-2=-2x-7$ da $5x=-5$, por tanto $x=-1$."}, {title: "3. Comprobación", body: "Para $x=9$, ambos valores absolutos valen $25$. Para $x=-1$, ambos valen $5$."}],
    finalAnswer: "El conjunto solución es $\\{-1,9\\}$.", commonMistake: "Igualar solo los interiores y olvidar el caso en que son opuestos.",
  },
  {
    slug: "introduccion-fracciones-parciales-repetidas", number: "08", course: "Introducción a las Matemáticas", courseSlug: "introduccion-matematicas", collection: "Ejercicios",
    title: "Fracciones parciales con un factor repetido", topic: "Fracciones parciales", difficulty: "Intermedio", estimatedTime: "12 min",
    statement: ["Descompón $\\frac{4x+6}{x^2+2x+1}$ en fracciones parciales. Indica su dominio y verifica la descomposición."],
    relatedTheory: [{label: "Preparación y factores lineales", href: "/cursos/introduccion-matematicas#intro-polinomios-6"}, {label: "Guía de los cuatro casos", href: "/cursos/introduccion-matematicas#intro-polinomios-7"}],
    hints: ["Reconoce un cuadrado perfecto en el denominador.", "Para $(x+1)^2$ necesitas $\\frac A{x+1}+\\frac B{(x+1)^2}$; no basta usar la potencia más alta.", "Multiplica por $(x+1)^2$ y compara los coeficientes de $4x+6=A(x+1)+B$."],
    solution: [{title: "1. Dominio y factorización", body: "$x^2+2x+1=(x+1)^2$, por lo que $x\\ne-1$."}, {title: "2. Coeficientes", body: "$4x+6=Ax+A+B$. Entonces $A=4$ y $A+B=6$, de donde $B=2$."}, {title: "3. Verificación", body: "Al reunir las fracciones obtenemos $$\\frac4{x+1}+\\frac2{(x+1)^2}=\\frac{4(x+1)+2}{(x+1)^2}=\\frac{4x+6}{x^2+2x+1}.$$"}],
    finalAnswer: "$\\frac4{x+1}+\\frac2{(x+1)^2}$, con $x\\ne-1$.", commonMistake: "Omitir la fracción correspondiente a la primera potencia del factor repetido.",
  },
  {
    slug: "lineal-sistema-por-eliminacion", number: "09", course: "Álgebra Lineal", courseSlug: "algebra-lineal", collection: "Ejercicios",
    title: "Resolver un sistema por eliminación", topic: "Sistemas lineales", difficulty: "Inicial", estimatedTime: "10 min",
    statement: ["Resuelve el sistema mediante eliminación y comprueba la solución en ambas ecuaciones: $$\\begin{cases}x+y=3,\\\\2x-y=0.\\end{cases}$$"],
    relatedTheory: [{label: "Sistemas de ecuaciones lineales", href: "/cursos/algebra-lineal#unidad-3-seccion-1"}, {label: "Operaciones elementales", href: "/cursos/algebra-lineal#unidad-1-seccion-8"}],
    hints: ["Escribe la matriz aumentada: $$\\left(\\begin{array}{cc|c}1&1&3\\\\2&-1&0\\end{array}\\right).$$", "Reemplaza la segunda fila por $F_2-2F_1$ para eliminar $x$ de esa fila.", "La segunda fila representa $-3y=-6$. Recupera después $x$ usando la primera ecuación."],
    solution: [{title: "1. Eliminación", body: "La operación $F_2\\leftarrow F_2-2F_1$ produce $$\\left(\\begin{array}{cc|c}1&1&3\\\\0&-3&-6\\end{array}\\right).$$"}, {title: "2. Sustitución", body: "De $-3y=-6$ obtenemos $y=2$. Entonces $x+2=3$, así que $x=1$."}, {title: "3. Comprobación", body: "$1+2=3$ y $2\\cdot1-2=0$. Hay una solución única."}],
    finalAnswer: "$(x,y)=(1,2)$.", commonMistake: "Aplicar una operación de fila a los coeficientes pero no al término independiente.",
  },
  {
    slug: "lineal-inversa-dos-por-dos", number: "10", course: "Álgebra Lineal", courseSlug: "algebra-lineal", collection: "Ejercicios",
    title: "Calcular y comprobar una matriz inversa", topic: "Matrices e inversas", difficulty: "Inicial", estimatedTime: "12 min",
    statement: ["Sea $$A=\\begin{pmatrix}1&2\\\\3&5\\end{pmatrix}.$$ Calcula $A^{-1}$ y comprueba que $AA^{-1}=I$."],
    relatedTheory: [{label: "Inversa de una matriz", href: "/cursos/algebra-lineal#unidad-1-seccion-6"}, {label: "Matriz adjunta y cálculo de la inversa", href: "/cursos/algebra-lineal#unidad-2-seccion-3"}],
    hints: ["Antes de calcular la inversa, verifica que el determinante sea distinto de cero.", "Para $A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$, el determinante es $ad-bc$; su adjunta es $\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}$.", "Multiplica la adjunta por $\\frac1{\\det(A)}$ y verifica el producto fila por columna."],
    solution: [{title: "1. Determinante", body: "$\\det(A)=1\\cdot5-2\\cdot3=-1$. La matriz es invertible."}, {title: "2. Inversa", body: "La adjunta es $\\begin{pmatrix}5&-2\\\\-3&1\\end{pmatrix}$. Al dividir por $-1$, $$A^{-1}=\\begin{pmatrix}-5&2\\\\3&-1\\end{pmatrix}.$$"}, {title: "3. Producto", body: "El producto es la identidad: $$AA^{-1}=\\begin{pmatrix}-5+6&2-2\\\\-15+15&6-5\\end{pmatrix}=\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}=I.$$"}],
    finalAnswer: "$A^{-1}=\\begin{pmatrix}-5&2\\\\3&-1\\end{pmatrix}$.", commonMistake: "Olvidar dividir la adjunta por el determinante o invertir los signos equivocados.",
  },
  {
    slug: "diferencial-dominio-raiz", number: "11", course: "Cálculo Diferencial", courseSlug: "calculo-diferencial", collection: "Ejercicios",
    title: "Dominio y cortes de una función con raíz", topic: "Funciones y dominio", difficulty: "Inicial", estimatedTime: "10 min",
    statement: ["Determina el dominio real y los cortes con los ejes de $h(x)=\\sqrt{x^2-x-30}$."],
    relatedTheory: [{label: "Funciones elementales y transformaciones", href: "/cursos/calculo-diferencial#funciones-seccion-2"}],
    hints: ["Para que la raíz cuadrada sea real, el radicando debe ser mayor o igual que cero.", "Factoriza $x^2-x-30=(x+5)(x-6)$ y analiza el signo entre sus raíces.", "Para el eje $x$, impón $h(x)=0$. Para el eje $y$, revisa primero si $x=0$ pertenece al dominio."],
    solution: [{title: "1. Signo del radicando", body: "Los factores se anulan en $-5$ y $6$. Su producto es no negativo para $x\\le-5$ o $x\\ge6$."}, {title: "2. Cortes con el eje x", body: "La raíz vale cero exactamente en $x=-5$ y $x=6$: los puntos son $(-5,0)$ y $(6,0)$."}, {title: "3. Eje y", body: "En $x=0$ el radicando sería $-30$. Como $0$ no está en el dominio, no hay corte con el eje $y$."}],
    finalAnswer: "Dominio: $(-\\infty,-5]\\cup[6,\\infty)$. Cortes: $(-5,0)$ y $(6,0)$; ninguno con el eje $y$.", commonMistake: "Exigir radicando estrictamente positivo y excluir los puntos donde la raíz vale cero.",
  },
  {
    slug: "diferencial-continuidad-por-tramos", number: "12", course: "Cálculo Diferencial", courseSlug: "calculo-diferencial", collection: "Ejercicios",
    title: "Unir tres tramos con continuidad", topic: "Límites y continuidad", difficulty: "Intermedio", estimatedTime: "15 min",
    statement: ["Determina $a$ y $b$ para que $f$ sea continua en todo $\\mathbb R$: $$f(x)=\\begin{cases}2x-a,&x<-3,\\\\ax+2b,&-3\\le x\\le3,\\\\b-5x,&x>3.\\end{cases}$$"],
    relatedTheory: [{label: "Álgebra de límites y continuidad", href: "/cursos/calculo-diferencial#limites-seccion-2"}],
    hints: ["Cada tramo es un polinomio. Solo necesitas revisar las uniones $x=-3$ y $x=3$.", "Iguala los valores que entregan las expresiones vecinas en cada unión.", "En $-3$ obtienes $-6-a=-3a+2b$; en $3$, $3a+2b=b-15$. Resuelve el sistema."],
    solution: [{title: "1. Primera unión", body: "$-6-a=-3a+2b$ equivale a $a-b=3$."}, {title: "2. Segunda unión", body: "$3a+2b=b-15$ equivale a $3a+b=-15$. Sumando ambas ecuaciones: $4a=-12$. Así $a=-3$ y $b=-6$."}, {title: "3. Verificación", body: "Con esos valores, ambos límites laterales y $f(-3)$ valen $-3$; en $x=3$, ambos límites laterales y $f(3)$ valen $-21$."}],
    finalAnswer: "$a=-3$ y $b=-6$.", commonMistake: "Comprobar solo una unión: la continuidad se debe cumplir en las dos.",
  },
  {
    slug: "edo-separable-valor-inicial", number: "13", course: "Ecuaciones Diferenciales", courseSlug: "ecuaciones-diferenciales", collection: "Ejercicios",
    title: "Una ecuación separable con valor inicial", topic: "Variables separables", difficulty: "Inicial", estimatedTime: "12 min",
    statement: ["Resuelve $y'=2xy$ con $y(0)=3$. Comprueba la ecuación diferencial y la condición inicial."],
    relatedTheory: [{label: "Variables separables", href: "/cursos/ecuaciones-diferenciales#clase-1-seccion-4"}, {label: "Problemas de valores iniciales", href: "/cursos/ecuaciones-diferenciales#clase-1-seccion-3"}],
    hints: ["Separa las variables: para $y\\ne0$, escribe $\\frac{dy}{y}=2x\\,dx$. La solución $y=0$ no cumple el dato inicial.", "Integra ambos lados: $\\ln|y|=x^2+C$. Escribe después $y=Ke^{x^2}$.", "Usa $y(0)=3$ para encontrar $K$ y deriva la función resultante para verificarla."],
    solution: [{title: "1. Integración", body: "Separando e integrando obtenemos $\\ln|y|=x^2+C$, así que $y=Ke^{x^2}$."}, {title: "2. Dato inicial", body: "Al sustituir $x=0$, $3=Ke^0=K$."}, {title: "3. Verificación", body: "La derivada de $y=3e^{x^2}$ es $6xe^{x^2}=2xy$. Además, $y(0)=3$. Está definida en todo $\\mathbb R$."}],
    finalAnswer: "$y(x)=3e^{x^2}$, para todo $x$ real.", commonMistake: "Confundir $e^{x^2}$ con $e^{2x}$, o no usar el dato inicial para fijar la constante.",
  },
  {
    slug: "edo-lineal-factor-integrante", number: "14", course: "Ecuaciones Diferenciales", courseSlug: "ecuaciones-diferenciales", collection: "Ejercicios",
    title: "Resolver con un factor integrante", topic: "Ecuaciones lineales de primer orden", difficulty: "Intermedio", estimatedTime: "15 min",
    statement: ["Resuelve $y'+2y=e^x$ con $y(0)=0$ mediante un factor integrante."],
    relatedTheory: [{label: "Ecuaciones diferenciales lineales", href: "/cursos/ecuaciones-diferenciales#clase-2-seccion-2"}],
    hints: ["La ecuación tiene la forma $y'+p(x)y=q(x)$, con $p(x)=2$. Calcula $\\mu(x)=e^{\\int p(x)\\,dx}$.", "Multiplica toda la ecuación por $e^{2x}$. El lado izquierdo se convierte en la derivada de $e^{2x}y$.", "Integra $(e^{2x}y)'=e^{3x}$, despeja $y$ y aplica $y(0)=0$."],
    solution: [{title: "1. Factor integrante", body: "$\\mu(x)=e^{2x}$, por lo que $(e^{2x}y)'=e^{3x}$."}, {title: "2. Integración", body: "$e^{2x}y=\\frac{e^{3x}}3+C$. Despejando: $y=\\frac{e^x}3+Ce^{-2x}$."}, {title: "3. Condición y comprobación", body: "$y(0)=0$ implica $C=-\\frac13$. Entonces $y'=\\frac{e^x}3+\\frac{2e^{-2x}}3$, y al sumar $2y$ obtenemos $e^x$."}],
    finalAnswer: "$y(x)=\\frac{e^x-e^{-2x}}3$, para todo $x$ real.", commonMistake: "Multiplicar por el factor integrante solo el lado izquierdo y dejar intacto el término $e^x$.",
  },
];
