import type { Exercise, ExerciseDifficulty } from "./exercises";
const r=String.raw;
function g(title:string,difficulty:ExerciseDifficulty,hints:string[],bodies:string[],finalAnswer:string):Partial<Exercise>{return {title,difficulty,hints,solution:bodies.map(body=>({body})),finalAnswer};}
const tangentHints=[r`Comprueba primero que el punto pertenece a la curva.`,r`Deriva; si la ecuación es implícita, trata $y$ como función de $x$.`,r`Usa $y-y_0=m(x-x_0)$. Para la normal, la pendiente es $-1/m$ cuando $m\ne0$.`];
const ruleHints=[r`Identifica las operaciones exteriores antes de derivar.`,r`Aplica las reglas de producto, cociente y cadena según corresponda.`,r`Conserva los factores de las derivadas interiores y revisa el dominio.`];
const limitHints=[r`Comprueba si puedes sustituir directamente o aparece una indeterminación.`,r`En cocientes de polinomios al infinito compara los grados; en diferencias usa factorización o racionalización.`,r`Una expresión de la forma $(f(a+h)-f(a))/h$ puede reconocerse como una derivada.`];
const domainHints=[r`Los denominadores no pueden ser cero y los radicandos de raíces pares deben ser no negativos.`,r`Para el recorrido plantea $y=f(x)$ y analiza qué valores de $y$ son posibles.`,r`Comprueba que cada valor permitido de $y$ tiene una preimagen en el dominio.`];
const asymHints=[r`Factoriza y distingue ceros cancelables de polos.`,r`En cada polo estudia el signo de los límites laterales.`,r`Divide los polinomios para estudiar el comportamiento al infinito; verifica que la diferencia con la recta tienda a cero.`];
const implicitHints=[r`Antes de derivar, comprueba que la ecuación define puntos reales.`,r`Deriva ambos miembros con la regla de la cadena y agrupa los términos con $y'$.`,r`No dividas por un factor nulo. Revisa por separado los puntos singulares.`];
const sinxy=r`En números reales, $\sin u=u$ solo para $u=0$: para $u>0$, $u-\sin u=\int_0^u(1-\cos t)\,dt>0$, y por simetría tampoco hay otra raíz negativa. Por tanto $xy=0$. La rama $y=0$ tiene derivada $0$; la recta $x=0$ es vertical y no es una gráfica $y(x)$. En el origen se cruzan ambas ramas, de modo que no hay una tangente única para toda la curva.`;
const sqrtxy=r`Para $\sqrt{x+y}=xy$ se exige $x+y\ge0$, $xy\ge0$. Cuando $x+y>0$, $(1+y')/(2\sqrt{x+y})=y+xy'$, luego $y'=(2y\sqrt{x+y}-1)/(1-2x\sqrt{x+y})$ si el denominador no es cero. El único punto con $x+y=0$ es $(0,0)$; al cuadrar se obtiene $x+y=x^2y^2$ y la rama local tiene pendiente $-1$, pero salvo el origen tiene $xy<0$. Así el origen está aislado en la curva original y no define una derivada $y(x)$.`;
const noExp=r`La ecuación $y=e^x+e^y$ no tiene puntos reales: $e^y\ge1+y$ implica $y-e^y\le-1$, mientras que $e^x>0$. Por tanto no hay una función real que derivar. La manipulación formal $y'=e^x/(1-e^y)$ no representa una solución real.`;
function exponential(hashTitle:string,a:number,b:number){return g(hashTitle,"Inicial",[r`La derivada de una exponencial compuesta introduce el factor de su exponente lineal.`,r`Repite el cálculo para reconocer una potencia del mismo factor.`,r`Justifica la fórmula general por inducción sobre el orden de derivación.`],[`$f'=${a}e^{${a}x+(${b})}$, $f''=${a*a}e^{${a}x+(${b})}$, $f'''=${a**3}e^{${a}x+(${b})}$ y $f^{(4)}=${a**4}e^{${a}x+(${b})}$. Cada derivación multiplica por $${a}$, por lo que $f^{(n)}=${a}^n e^{${a}x+(${b})}$ para todo entero $n\\ge0$.`],`$f^{(n)}=${a}^n e^{${a}x+(${b})}$.`);}
export const calculusGuidance:Record<string,Partial<Exercise>>={
  "8caca28938b7":g("Continuidad · ocho funciones racionales y sus extensiones","Intermedio",limitHints,[
    r`Cada expresión es continua donde está definida. Para reparar un punto excluido se necesita un límite finito; se define allí ese valor y se conserva la expresión fuera del punto.`,
    r`1. En $x=\pm2$ hay polos: no se reparan. 2. Fuera de $2$, la función es $(x^2+2x+4)/5$; se repara definiendo $\widetilde f(2)=12/5$.`,
    r`3. Factorizando se reduce a $(x-4)/(x-2)$, con exclusiones originales $-4,2$. Se repara $-4$ con valor $4/3$, pero $2$ es un polo.`,
    r`4. Se reduce a $(x^2-3x+9)/2$, y se repara $-3$ asignándole $27/2$. 5. Se reduce a $(x+1)/(x+2)$; se repara $1$ con valor $2/3$, pero $-2$ es un polo.`,
    r`6. En $0$ hay un polo, no reparable. 7. Se reduce a $(x-5)/(x-3)$; se repara $-5$ asignándole $5/4$, pero $3$ es un polo.`,
    r`8. Para $x\ne1$, $f=x+1+\sin(x-1)/(x-1)$. Al tender $x$ a $1$, el límite es $2+1=3$. Se define $\widetilde f(1)=3$ para obtener continuidad en todo $\mathbb R$.`
  ],r`Puntos reparables y valores: inciso 2, $(2,12/5)$; 3, $(-4,4/3)$; 4, $(-3,27/2)$; 5, $(1,2/3)$; 7, $(-5,5/4)$; 8, $(1,3)$. Los restantes puntos excluidos son polos.`),
  "ab09d0720b60":g("Asíntotas · seis funciones y denominadores de grado alto","Desafío",asymHints,[
    r`1. $3/(4-x^2)$ tiene horizontal $y=0$ y verticales $x=\pm2$. En $-2$ los límites izquierdo/derecho son $-\infty,+\infty$; en $2$ son $+\infty,-\infty$.`,
    r`2. Para $x\ne2$, $f=(x^2+2x+4)/5$. En $2$ hay un hueco con límite $12/5$; no hay asíntotas verticales, horizontales ni oblicuas rectilíneas.`,
    r`3. El denominador $d=x^4-x^3+2$ tiene mínimo global en $x=3/4$ con valor $2-27/256>0$, así que no hay polos reales. La división da $f=x-2x/d$, y $f-x\to0$ en ambos infinitos: oblicua $y=x$, sin horizontal.`,
    r`4. Sea $d(x)=5x^3-8x+1$. Tiene exactamente tres raíces simples $a_1\in(-2,-1)$, $a_2\in(0,1/2)$ y $a_3\in(1,2)$: hay una en cada intervalo por cambio de signo y el grado es tres. El numerador cumple $N=-2d/5+(17-36x)/5$ y no se anula en esas raíces, porque $d(17/36)\ne0$. Las tres rectas $x=a_i$ son verticales. Cerca de cada raíz, $f(x)\sim c_i/(x-a_i)$, con $c_i=(17-36a_i)/(5(15a_i^2-8))\ne0$, lo que da límites laterales infinitos de signos opuestos. La horizontal es $y=-2/5$.`,
    r`5. Para $x\ne-3$, $f=(x^2-3x+9)/2$; hay un hueco de límite $27/2$ y ninguna asíntota rectilínea de las solicitadas.`,
    r`6. $d(x)=5x^3-x+3$ tiene una única raíz real $a\in(-1,0)$. Sus extremos locales, en $\pm1/\sqrt{15}$, tienen ambos valores positivos, por lo que solo cruza el eje una vez. El numerador en $a$ es $(59-13a)/5>0$ y $d'(a)>0$; por tanto los límites en $a^-,a^+$ son $-\infty,+\infty$. La vertical es $x=a$ y la horizontal $y=7/5$.`
  ],r`1. Verticales $\pm2$, horizontal $0$. 2. Ninguna. 3. Oblicua $y=x$. 4. Tres verticales en las raíces de $5x^3-8x+1$ y horizontal $-2/5$. 5. Ninguna. 6. Una vertical en la raíz de $5x^3-x+3$ y horizontal $7/5$.`),
  "4e633a156f71":g("Límites · cociente de polinomios y derivada del logaritmo","Inicial",limitHints,[r`1. Dividiendo numerador y denominador por $x^3$, el límite es $7/5$.`,r`2. Si $a>0$, es la definición de la derivada de $\ln x$ en $a$, cuyo valor es $1/a$. Si $a\le0$, $\ln a$ no está definido en los reales, por lo que el límite escrito no es una expresión real válida.`],r`1. $7/5$. 2. $1/a$ para $a>0$.`),
  "1a73c47958de":g("Límites · polinomios y diferencia de exponenciales","Inicial",limitHints,[r`1. Al dividir por $x^3$, se obtiene $7/5$.`,r`2. Escribe $(e^{ax}-1)/x-(e^{bx}-1)/x$. Cada término es un cociente incremental en cero, con límites $a$ y $b$ respectivamente.`],r`1. $7/5$. 2. $a-b$.`),
  "8b24181746d3":g("Tangente a una curva implícita con seno","Intermedio",tangentHints,[r`En $(\pi,0)$, el lado izquierdo es $0+\sin\pi+3\pi^2=3\pi^2$.`,r`Derivando: $2yy'+\cos(x+y)(1+y')+6x=0$. En el punto queda $-(1+y')+6\pi=0$, así $m=6\pi-1$.`],r`$y=(6\pi-1)(x-\pi)$.`),
  "47e32d6cd43b":g("Tangente implícita con raíces cúbicas","Intermedio",tangentHints,[r`El punto verifica $1-1+2=2$. Cerca de $(1,-1)$ se puede derivar: $\frac{2}{3\sqrt[3]x}-\frac{2y'}{3\sqrt[3]y}-2y'=0$.`,r`Sustituyendo resulta $2/3+(2/3)y'-2y'=0$, luego $y'=1/2$.`],r`$y+1=\frac12(x-1)$.`),
  "fa3f94e00490":g("Producto y segunda derivada de una exponencial de seno","Intermedio",ruleHints,[r`$f'=2\cos(2x)e^{\sin(2x)}$. Por producto y cadena, $f''=4e^{\sin(2x)}(\cos^2(2x)-\sin(2x))$.`,r`Como $g=xf'$, $g'=f'+xf''$.`],r`$g'=e^{\sin(2x)}[2\cos(2x)+4x(\cos^2(2x)-\sin(2x))]$.`),
  "fd592a0bcfe5":g("Producto y segunda derivada de una exponencial de coseno","Intermedio",ruleHints,[r`$f'=-2\sin(2x)e^{\cos(2x)}$ y $f''=4e^{\cos(2x)}(\sin^2(2x)-\cos(2x))$.`,r`Derivando $g=xf'$ se obtiene $g'=f'+xf''$.`],r`$g'=e^{\cos(2x)}[-2\sin(2x)+4x(\sin^2(2x)-\cos(2x))]$.`),
  "4ac098d97f17":g("Pendiente de una curva paramétrica trigonométrica","Intermedio",[r`Calcula $x'(t)$ e $y'(t)$.`,r`Usa $dy/dx=y'(t)/x'(t)$ cuando $x'(t)\ne0$.`,r`Sustituye $t=\pi/6$ después de derivar.`],[r`$x'=2(1-\cos t)$, $y'=4t-6t^2$. En $t=\pi/6$, el denominador es $2-\sqrt3>0$ y el numerador $2\pi/3-\pi^2/6$.`],r`$\frac{dy}{dx}=\frac{\pi(4-\pi)}{6(2-\sqrt3)}$.`),
  "05f92038a429":g("Pendiente de una curva paramétrica polinómica","Inicial",[r`Deriva las dos coordenadas respecto de $t$.`,r`Divide $y'(t)$ entre $x'(t)$.`,r`Verifica que $x'(-1)\ne0$.`],[r`$x'=2+6t$ e $y'=2t+6t^2=t(2+6t)$. En $t=-1$, $x'=-4$, $y'=4$ y el punto es $(1,-1)$.`],r`$dy/dx=-1$.`),
  "a1f7296f7eae":g("Derivada por definición · exponencial","Intermedio",limitHints,[r`$\frac{f(x+h)-f(x)}h=e^{2x}\frac{e^{2h}-1}h$. Haciendo $u=2h$, el segundo factor es $2(e^u-1)/u\to2$.`],r`$f'(x)=2e^{2x}$ para todo $x\in\mathbb R$.`),
  "6b1ccaa9695e":g("Derivada por definición · polinomio cuadrático","Inicial",[r`Escribe $[f(x+h)-f(x)]/h$.`,r`Desarrolla $(x+h)^2$ y cancela los términos independientes de $h$.`,r`Simplifica antes de tomar $h\to0$.`],[r`$[f(x+h)-f(x)]/h=(2xh+h^2+3h)/h=2x+h+3$. Al tomar $h\to0$ resulta $2x+3$.`],r`$f'(x)=2x+3$.`),
  "d1f82d585ac5":g("Derivada por definición · polinomio cúbico","Inicial",[r`Desarrolla $(x+h)^3$.`,r`Cancela $x^3$ y divide por $h\ne0$.`,r`Toma el límite cuando $h\to0$.`],[r`$[f(x+h)-f(x)]/h=(3x^2h+3xh^2+h^3)/h=3x^2+3xh+h^2\to3x^2$.`],r`$f'(x)=3x^2$.`),
  "1494be279af4":g("Derivada por definición · raíz cuadrada","Intermedio",[r`El dominio es $x\ge-3$; para la derivada usual trabaja en $x>-3$.`,r`Racionaliza la diferencia de raíces con su conjugado.`,r`Cancela $h$ antes de tomar el límite.`],[r`Para $x>-3$, $\frac{\sqrt{x+h+3}-\sqrt{x+3}}h=\frac1{\sqrt{x+h+3}+\sqrt{x+3}}\to\frac1{2\sqrt{x+3}}$. En $x=-3$ el cociente lateral es $1/\sqrt h\to+\infty$, de modo que no hay derivada finita.`],r`$f'(x)=1/(2\sqrt{x+3})$ para $x>-3$.`),
  "12adf7e08243":g("¿Existe una tangente con pendiente dos?","Intermedio",tangentHints,[r`$f'(x)=2x/(x^2+2)$. Imponer $f'(x)=2$ da $x=x^2+2$, es decir $x^2-x+2=0$. Su discriminante es $1-8=-7<0$. No existe ningún punto real que cumpla esa pendiente.`],"No existe una recta tangente con la pendiente solicitada."),
  "8857864f484a":g("Recta normal a una exponencial compuesta","Intermedio",tangentHints,[r`$f(1)=e^{5/2}$ y $f'(x)=e^{x/2+2/x}(1/2-2/x^2)$. Así $f'(1)=-3e^{5/2}/2$ y la pendiente normal es $2/(3e^{5/2})$.`],r`La normal en el punto indicado es $y-e^{5/2}=\frac{2}{3e^{5/2}}(x-1)$.`),
  "3087328e4d84":g("Tangente horizontal a una raíz compuesta","Inicial",tangentHints,[r`$f(0)=1$. Cerca de cero, $f'(x)=(2x-\sin x)/(2\sqrt{x^2+\cos x})$, por lo que $f'(0)=0$.`],r`La tangente en $(0,f(0))$ es $y=1$.`),
  "065597daf6f6":g("Tangente paralela a una recta dada","Intermedio",tangentHints,[r`La recta dada tiene pendiente $-1$. Como $f'(x)=x^2+2x$, imponemos $x^2+2x=-1$, o $(x+1)^2=0$.`,r`En $x=-1$, $f(-1)=2/3$. La tangente es $y-2/3=-(x+1)$.`],r`$y=-x-1/3$.`),
  "517266d4e3d6":g("Derivadas sucesivas del logaritmo","Intermedio",[r`Trabaja en el dominio $x>1$.`,r`Escribe las primeras derivadas como potencias negativas de $x-1$.`,r`Reconoce el signo alternado y el factorial.`],[r`$f'=1/(x-1)$, $f''=-1/(x-1)^2$, $f'''=2/(x-1)^3$, $f^{(4)}=-6/(x-1)^4$. Cada derivación multiplica por el exponente negativo y cambia el signo. Por inducción, $f^{(n)}=(-1)^{n-1}(n-1)!/(x-1)^n$ para $n\ge1$.`],r`$f^{(n)}(x)=\frac{(-1)^{n-1}(n-1)!}{(x-1)^n}$, $x>1$, $n\ge1$.`),
  "4e27cbea56d9":exponential("Derivadas sucesivas · exponencial de 7x + 6",7,6),
  "1ec206390441":exponential("Derivadas sucesivas · exponencial de 5x − 1",5,-1),
  "45441e72664f":g("Verificar una solución de una ecuación diferencial","Inicial",ruleHints,[r`$y'=e^x(\sin x+\cos x)$ y $y''=2e^x\cos x$. Entonces $2y'-y''-2y=2e^x(\sin x+\cos x)-2e^x\cos x-2e^x\sin x=0$.`],r`Sí, $y=e^x\sin x$ satisface la ecuación para todo $x\in\mathbb R$.`),
  "5d22f5939d25":g("Existencia de una raíz por continuidad","Inicial",[r`Define el polinomio como una función continua.`,r`Calcula su signo en los extremos.`,r`Aplica el teorema del valor intermedio.`],[r`$p(x)=2x^3-2x^2-4x+1$ es continuo en $[-2,2]$. Se tiene $p(-2)=-15$ y $p(2)=1$. Como $0$ está entre esos valores, existe $c\in(-2,2)$ con $p(c)=0$.`],r`Existe al menos una raíz en $(-2,2)$.`),
  "6725a8822eb7":g("Derivación implícita · factorización y puntos singulares","Desafío",implicitHints,[r`1. $y^2+y=x^2+x$ equivale a $(y-x)(y+x+1)=0$. Las ramas son $y=x$ y $y=-x-1$, de pendientes $1$ y $-1$. La fórmula $y'=(2x+1)/(2y+1)$ sirve fuera del cruce $(-1/2,-1/2)$; allí no existe una tangente única de toda la curva.`,"2. "+sinxy],r`1. Pendientes $1$ y $-1$ según la rama. 2. Rama horizontal de pendiente $0$ y rama vertical; revisar sus cruces.`),
  "a9ce301e3cc8":g("Derivación implícita · dominio real y singularidades","Desafío",implicitHints,["1. "+sqrtxy,"2. "+noExp],r`1. $y'=(2y\sqrt{x+y}-1)/(1-2x\sqrt{x+y})$ en puntos regulares. 2. No hay soluciones reales.`),
  "80a4f5d339a1":g("Derivación implícita · ocho casos y sus dominios","Desafío",implicitHints,[
    r`1. Para $x,y>0$, $y'\ln x+y/x+\ln y+xy'/y=0$, luego $y'=-(y/x+\ln y)/(\ln x+x/y)$ donde el denominador no sea cero.`,"2. "+sinxy,
    r`3. Si $u=xy>0$, la desigualdad $\ln u\le u-1<u$ impide $\ln(xy)=xy$. No hay puntos reales.`,"4. "+noExp,"5. "+sqrtxy,
    r`6. Para $xy\ne0$, la ecuación equivale a $x^4=y^4$, de modo que $y=x$ o $y=-x$. Sus derivadas son $1$ y $-1$, respectivamente.`,
    r`7. $(y-x)(y+x+1)=0$: las ramas son $y=x$ e $y=-x-1$, de derivadas $1$ y $-1$. En su intersección $(-1/2,-1/2)$ no hay tangente única de toda la curva.`,
    r`8. Con $y\ne0$, multiplica por $y$: $y^2=x-x^3y$. Derivando, $(2y+x^3)y'=1-3x^2y$, luego $y'=(1-3x^2y)/(2y+x^3)$ donde el denominador no sea cero.`
  ],"Las derivadas y excepciones de dominio están indicadas en los ocho incisos; los incisos 3 y 4 no tienen puntos reales."),
  "938df7613ee7":g("Tangentes y normales · seis curvas implícitas","Desafío",tangentHints,[
    r`Al sustituir los puntos, los lados izquierdos son respectivamente $30$, $12$, $1$, $4$, $2$ y $5$: todos pertenecen a sus curvas.`,
    r`1. $y'=-(3x^2y+y^3)/(x^3+3xy^2)$; en $(1,3)$, $m=-9/7$. Tangente: $y-3=-9(x-1)/7$. Normal: $y-3=7(x-1)/9$.`,
    r`2. Derivando se obtiene $(2x^2y+4x-12)y'=-(2xy^2+4y)$. En $(2,1)$, $m=-2$. Tangente: $y-1=-2(x-2)$. Normal: $y-1=(x-2)/2$.`,
    r`3. $\cos(xy)(y+xy')=y'$. En $(\pi/2,1)$, $m=0$. Tangente $y=1$ y normal vertical $x=\pi/2$.`,
    r`4. $y'-\sin(xy^2)(y^2+2xyy')+6x=0$. En $(1,0)$, $m=-6$. Tangente $y=-6(x-1)$ y normal $y=(x-1)/6$.`,
    r`5. $2/(3\sqrt[3]x)-2y'/(3\sqrt[3]y)-2y'=0$. En $(1,-1)$, $m=1/2$. Tangente $y+1=(x-1)/2$ y normal $y+1=-2(x-1)$.`,
    r`6. $y'/(2\sqrt y)+y^2+2xyy'=0$. En $(4,1)$, $m=-2/17$. Tangente $y-1=-2(x-4)/17$ y normal $y-1=17(x-4)/2$.`
  ],r`Pendientes tangentes: $-9/7,-2,0,-6,1/2,-2/17$; las seis rectas normales se detallan arriba.`),
  "01fc90b37ad8":g("Reglas de derivación · cociente y cadenas de raíces","Intermedio",ruleHints,[r`1. Por cociente, $f'=\frac{2x(x-1)/(x^2+1)-\ln(x^2+1)}{(x-1)^2}$, $x\ne1$.`,r`2. Por cadena, $f'=(x+1)\cos(\sqrt{x^2+2x-15})/\sqrt{x^2+2x-15}$ para $x<-5$ o $x>3$. En los extremos del dominio no hay derivada finita.`,r`3. Sea $u=\cos^2x+2x$. Por producto y cadena, $h'=e^{x^2-25}[(1-\sin x\cos x)/\sqrt u+2x\sqrt u]$ cuando $u>0$.`],"Las tres derivadas se indican arriba, en los interiores de sus dominios."),
  "505737f7c9ca":g("Reglas de derivación · producto, cociente y logaritmo","Intermedio",ruleHints,[r`1. $f'=((x-1)\cos(x-1)-\sin(x-1))/(x-1)^2$, para $x\ne1$.`,r`2. $f'=e^{5x^3-x+3}[(21x^2-4)+(7x^3-4x+16)(15x^2-1)]$.`,r`3. Escribe $h=\frac12\ln(9-\cos^2x)$. Entonces $h'=\sin x\cos x/(9-\cos^2x)$, para todo $x\in\mathbb R$.`],"Las derivadas son las expresiones obtenidas en los tres incisos."),
  "7ec53692de0c":g("Reglas de derivación · raíces, exponencial y producto","Intermedio",ruleHints,[r`1. $h'=\frac{(6x^2-5)(x^2+x+1)-(2x^3-5x)(2x+1)}{(x^2+x+1)^2}$ para todo $x\in\mathbb R$.`,r`2. $f'=e^{\sqrt[3]{x^2+6}}\frac{2x}{3(x^2+6)^{2/3}}$.`,r`3. Para $x>0$, $h'=(1/(2\sqrt x)+\cos x)\ln(3x^2+1)+(\sqrt x+\sin x)6x/(3x^2+1)$. En $x=0$ no hay derivada bilateral por ser extremo del dominio; la derivada por la derecha es $0$, pues $h(x)/x$ tiende a cero.`],"Las tres derivadas se indican arriba, incluyendo la salvedad en el extremo del dominio."),
  "f1bfced50854":g("Rectas tangentes · cuatro funciones explícitas","Inicial",tangentHints,[r`1. $f(1)=2$, $f'(1)=2$: $y=2x$.`,r`2. $f(1)=2$, $f'(1)=-3$: $y=-3x+5$.`,r`3. $f(3)=10/3$, $f'(3)=8/9$: $y=8x/9+2/3$.`,r`4. $f(-4)=-60$, $f'(-4)=47$: $y=47x+128$.`],r`$y=2x$; $y=-3x+5$; $y=8x/9+2/3$; $y=47x+128$, respectivamente.`),
  "32dee0cf5bcb":g("Límites · factorización, racionalización y grados","Intermedio",limitHints,[r`1. Cancela $x-2$: $(x^2+2x+4)/5\to12/5$.`,r`2. Racionaliza: $1/(\sqrt{x-2}+2)\to1/4$.`,r`3. Cancela $x+4$: $(x-4)/(x-2)\to4/3$.`,r`4. El cociente es $x-2x/(x^4-x^3+2)$, cuyo límite es $+\infty$.`,r`5. Grados iguales: límite $-2/5$.`,r`6. Cancela $x+3$: $(x^2-3x+9)/2\to27/2$.`,r`7. Racionaliza: $1/(\sqrt{x+7}+3)\to1/6$.`,r`8. Grados iguales: límite $7/5$.`],r`$12/5,1/4,4/3,+\infty,-2/5,27/2,1/6,7/5$.`),
  "c6c7dda530b3":g("Asíntotas · cancelación y división polinómica","Desafío",asymHints,[r`El denominador es $(x-1)(x-5)(x+2)$. Para $x\ne1$, se reduce a $-x^2(x+1)/((x-5)(x+2))$. En $x=1$ hay un hueco con límite $1/6$, no una asíntota.`,r`En $x=5$ y $x=-2$ hay polos con coeficientes de $(x-a)^{-1}$ negativos: los límites por la izquierda son $+\infty$ y por la derecha $-\infty$.`,r`La división da $f(x)=-x-4+(-22x-40)/(x^2-3x-10)$. Por tanto $f(x)-(-x-4)\to0$ cuando $x\to\pm\infty$. No hay horizontal.`],r`Verticales: $x=-2,5$. Oblicua: $y=-x-4$. Hueco en $x=1$.`),
  "2f264b1ece76":g("Asíntotas · dos polos y una oblicua","Desafío",asymHints,[r`El denominador es $2(x+4)(x-1)$ y no hay cancelaciones. En ambos polos los coeficientes de $(x-a)^{-1}$ son positivos, así que los límites por izquierda son $-\infty$ y por derecha $+\infty$.`,r`$f(x)=\frac52x-5+\frac{55x-40}{2x^2+6x-8}$. El último término tiende a cero en ambos infinitos; no hay asíntota horizontal.`],r`Verticales $x=-4,1$ y oblicua $y=5x/2-5$.`),
  "05761fde9f6e":g("Asíntotas · hueco y polo tras factorizar","Intermedio",asymHints,[r`$f(x)=(x+1)(x+2)/(3(x-2))$ para $x\ne-3,2$. En $x=-3$ el límite es $-2/15$ y hay un hueco.`,r`$f(x)=(x+5)/3+4/(x-2)$. En $2^-$ tiende a $-\infty$, y en $2^+$ a $+\infty$. La diferencia con $(x+5)/3$ tiende a cero en ambos infinitos.`],r`Vertical $x=2$; oblicua $y=(x+5)/3$. No hay horizontal; $x=-3$ es un hueco.`),
  "f0c250500f75":g("Asíntotas · función racional con un hueco","Intermedio",asymHints,[r`Factorizando se obtiene $f(x)=-2(x-2)(x+1)/((x-3)(x+2))$, conservando las exclusiones originales $x=1,3,-2$. En $x=1$ el límite es $-2/3$: hay hueco.`,r`En $x=-2$, los límites izquierdo y derecho son $-\infty,+\infty$. En $x=3$, son $+\infty,-\infty$. Los grados iguales dan límite $-2$ en ambos infinitos. No hay oblicua de pendiente no nula.`],r`Verticales $x=-2,3$; horizontal $y=-2$. Hueco en $x=1$.`),
  "b1262eeea1e9":g("Asíntotas · tres cocientes racionales","Intermedio",asymHints,[r`1. Para $x\ne1$, $f=(x+1)/(x+2)=1-1/(x+2)$. Vertical $x=-2$: límites $+\infty,-\infty$ por izquierda y derecha. Horizontal $y=1$; hueco en $x=1$ con límite $2/3$.`,r`2. $f=1/x+1/x^3$. Vertical $x=0$, con límites $-\infty,+\infty$. Horizontal $y=0$.`,r`3. Para $x\ne-5$, $f=(x-5)/(x-3)=1-2/(x-3)$. Vertical $x=3$, con límites $+\infty,-\infty$. Horizontal $y=1$; hueco en $x=-5$ con límite $5/4$. Ninguna tiene oblicua de pendiente no nula.`],r`1. $x=-2,y=1$. 2. $x=0,y=0$. 3. $x=3,y=1$.`),
  "c5c7a53172b9":g("Parábola · cortes y vértice","Inicial",domainHints,[r`$f(x)=-(x-1)^2+4=-(x-3)(x+1)$. Los cortes con $X$ son $(-1,0)$ y $(3,0)$; con $Y$, $(0,3)$.`,r`El vértice es $(1,4)$, el eje de simetría $x=1$ y la parábola abre hacia abajo. Para dibujarla marca esos puntos y su simétrico $(2,3)$; el recorrido es $(-\infty,4]$.`],r`Cortes $(-1,0),(3,0),(0,3)$; vértice $(1,4)$ y concavidad hacia abajo.`),
  "125283c2c5a2":g("Parábola · dominio, recorrido e inyectividad","Inicial",domainHints,[r`$g(x)=(x+3/2)^2-25/4=(x+4)(x-1)$. Dominio $\mathbb R$, recorrido $[-25/4,\infty)$. No es inyectiva: $g(0)=g(-3)=-4$.`,r`Cortes $(-4,0)$, $(1,0)$ y $(0,-4)$; vértice $(-3/2,-25/4)$. La gráfica es una parábola abierta hacia arriba, simétrica respecto de $x=-3/2$.`],r`Dominio $\mathbb R$, recorrido $[-25/4,\infty)$; no inyectiva. Vértice $(-3/2,-25/4)$.`),
  "bbee04920b7e":g("Inyectividad · contraejemplos y monotonía","Intermedio",[r`Para refutar inyectividad basta encontrar dos entradas distintas con la misma imagen.`,r`Una función estrictamente creciente en su dominio es inyectiva.`,r`No olvides restringir el dominio de las raíces.`],[r`1. No: $f(0)=f(2)=0$. 2. No: $f(-1)=f(1)=6$.`,r`3. Sí: $f'(x)=3x^2+1>0$ en $\mathbb R$. 4. Sí: la raíz cuadrada es estrictamente creciente en el dominio $[-1,\infty)$.`,r`5. No: el dominio es $[-3,3]$ y $f(-1)=f(1)=\sqrt8$.`],"En orden: no, no, sí, sí, no."),
  "cc838a6b8fe0":g("Modelo exponencial · depreciación de un equipo","Intermedio",[r`Evalúa el modelo en $t=0$ y $t=3$.`,r`Para el reemplazo iguala el valor a $500$.`,r`Despeja el exponente con logaritmo natural.`],[r`$V(0)=1500$ dólares y $V(3)=1500e^{-0.045}\approx1433.996$ dólares.`,r`$1500e^{-0.015t}=500$ equivale a $-0.015t=\ln(1/3)=-\ln3$, así $t=\ln3/0.015\approx73.241$ años.`],r`Valor inicial: $1500$ dólares; a los tres años: $1433.996$ dólares; reemplazo a los $73.241$ años aproximadamente.`),
  "ac9e99f143b0":g("Dominio y recorrido · cociente lineal","Inicial",domainHints,[r`Escribe $f(x)=2+9/(x-2)$. Se excluye $x=2$ y nunca se alcanza $y=2$. Para todo $y\ne2$, $x=2+9/(y-2)$ pertenece al dominio y verifica $f(x)=y$.`],r`Dominio $\mathbb R\setminus\{2\}$; recorrido $\mathbb R\setminus\{2\}$.`),
  "ac54adff0df4":g("Dominios · polinomios, cocientes y raíces","Inicial",domainHints,[r`1 y 4. Los polinomios tienen dominio $\mathbb R$. 2. $x^2+x+1=(x+1/2)^2+3/4>0$, luego el dominio es $\mathbb R$. 5. $x^2+1>0$, dominio $\mathbb R$.`,r`3. $(x-6)(x+5)\ge0$, así $x\le-5$ o $x\ge6$. 6. $(x-2)(x-3)\ge0$, así $x\le2$ o $x\ge3$.`],r`En orden: $\mathbb R$, $\mathbb R$, $(-\infty,-5]\cup[6,\infty)$, $\mathbb R$, $\mathbb R$, $(-\infty,2]\cup[3,\infty)$.`),
  "f109560db92e":g("Dominio y recorrido · recíproco de 2x − 3","Inicial",domainHints,[r`El denominador excluye $x=3/2$. El numerador no nulo impide $y=0$. Para cada $y\ne0$, $x=(3+5/y)/2$ verifica $f(x)=y$.`],r`Dominio $\mathbb R\setminus\{3/2\}$; recorrido $\mathbb R\setminus\{0\}$.`),
  "d99da5117b8d":g("Dominio y recorrido · recíproco de 9x − 7","Inicial",domainHints,[r`Se excluye $x=7/9$ por el denominador. Nunca se obtiene $y=0$. Para cualquier $y\ne0$, $x=(7+2/y)/9$ es una preimagen válida.`],r`Dominio $\mathbb R\setminus\{7/9\}$; recorrido $\mathbb R\setminus\{0\}$.`),
  "e3c66ff2a5a6":g("Masa de un resorte helicoidal","Intermedio",[r`La masa es $\int_C\rho\,ds$, no una integral de trabajo.`,r`Calcula $\|r'(t)\|$ y sustituye las coordenadas en la densidad.`,r`Usa $4\sin t\cos t=2\sin(2t)$.`],[r`La curva es un cuarto de hélice alrededor del eje $x$, sobre $y^2+z^2=4$, desde $(0,2,0)$ hasta $(\pi/2,0,2)$. Un punto intermedio es $(\pi/4,\sqrt2,\sqrt2)$.`,r`$r'=(1,-2\sin t,2\cos t)$ tiene norma $\sqrt5$. La densidad sobre la curva es $e^t+4\cos t\sin t\ge0$.`,r`$M=\sqrt5\int_0^{\pi/2}(e^t+2\sin2t)\,dt=\sqrt5[e^t-\cos2t]_0^{\pi/2}=\sqrt5(e^{\pi/2}+1)$.`],r`$M=\sqrt5(e^{\pi/2}+1)$ kg.`),
  "a7fd891e48f6":g("Ecuación diferencial · sustitución de x + y","Desafío",[r`Simplifica el cociente y usa $u=x+y$.`,r`Entonces $u'=1+y'=(2u+1)/(u+1)$: separa variables.`,r`Integra $\frac{u+1}{2u+1}=\frac12+\frac1{2(2u+1)}$ y aplica el dato inicial.`],[r`Con $u=x+y$, $u'= (2u+1)/(u+1)$, mientras $u\ne-1$. Separando, $\frac12u+\frac14\ln|2u+1|=x+C$. El dato $u(0)=0$ da $C=0$.`,r`La solución del problema inicial es la rama $u>-1/2$ de $2u+\ln(2u+1)=4x$. Esta expresión es estrictamente creciente de $-\infty$ a $+\infty$, por lo que determina un único $u$ para cada $x\in\mathbb R$. Luego $y=u-x$. La solución constante $u=-1/2$, excluida al separar, no cumple el dato inicial.`],r`$2(x+y)+\ln(2x+2y+1)=4x$, con $x+y>-1/2$.`),
  "dee435a0acde":g("Ecuación lineal · factor integrante trigonométrico","Intermedio",[r`En un intervalo con $\cos x\ne0$, divide por $\cos x$.`,r`Obtendrás $y'+\tan x\,y=\sec x$.`,r`Usa el factor integrante $\sec x$ en ese intervalo.`],[r`Multiplicar por $\sec x$ da $(y\sec x)'=\sec^2x$. Integrando, $y\sec x=\tan x+C$, y por tanto $y=\sin x+C\cos x$.`,r`La ecuación es lineal de primer orden y no homogénea. La familia hallada también satisface la ecuación original en los puntos $\cos x=0$, como se verifica sustituyendo $y'=\cos x-C\sin x$.`],r`$y(x)=\sin x+C\cos x$.`),
};
