import type { Exercise, ExerciseDifficulty } from "./exercises";
const r=String.raw;
function g(title:string,difficulty:ExerciseDifficulty,hints:string[],bodies:string[],finalAnswer:string):Partial<Exercise>{return {title,difficulty,hints,solution:bodies.map(body=>({body})),finalAnswer};}
const baseHints=[r`Escribe los polinomios mediante sus coordenadas en $\{1,x,x^2\}$.`,r`Coloca esos vectores como columnas de una matriz.`,r`Si el determinante es no nulo, son tres vectores independientes en un espacio de dimensión tres.`];
const baseProof=r`En la base canónica, las columnas de $1,x-a,(x-a)^2$ forman $\begin{pmatrix}1&-a&a^2\\0&1&-2a\\0&0&1\end{pmatrix}$. Su determinante es $1$, para todo $a\in\mathbb R$. Por tanto los tres polinomios son independientes y, como $\dim V=3$, forman una base.`;
const linearHints=[r`Escribe las imágenes de los vectores de la base como columnas.`,r`Usa que $T(\alpha u+\beta v)=\alpha T(u)+\beta T(v)$.`,r`Para núcleo, resuelve $T(v)=0$; para imagen, estudia el espacio generado por las columnas.`];
const orthHints=[r`Usa el producto interno dado, no uno distinto.`,r`Recuerda que $\|v\|=\sqrt{\langle v,v\rangle}$ y $d(u,v)=\|u-v\|$.`,r`La ortogonalidad equivale a producto interno cero.`];
const matrixHints=[r`Respeta el orden de los factores: las matrices no conmutan en general.`,r`Escribe cada entrada o aplica una identidad válida para matrices.`,r`Comprueba el resultado sustituyendo en la igualdad original.`];
const angle=g("Ángulo entre matrices con el producto de Frobenius","Intermedio",orthHints,[r`$\langle A,B\rangle=\operatorname{tr}(A^tB)=\sqrt2$, $\|A\|=\sqrt2$ y $\|B\|=\sqrt{2+1+1}=2$. Entonces $\cos\alpha=\sqrt2/(2\sqrt2)=1/2$.`],r`$\alpha=\pi/3=60^\circ$.`);
const functionDistance=g("Norma y distancia entre funciones continuas","Intermedio",orthHints,[r`$\|f\|^2=\int_0^1x^2\,dx=1/3$. Además $d(f,g)^2=\int_0^1(x-x^2)^2\,dx=1/3-1/2+1/5=1/30$.`],r`$\|f\|=1/\sqrt3$ y $d(f,g)=1/\sqrt{30}$.`);
export const linearGuidance:Record<string,Partial<Exercise>>={
  "17a17ce8d173":g("Base de polinomios trasladados","Inicial",baseHints,[baseProof],r`$S$ es una base para todo $a\in\mathbb R$.`),
  "0c23076adfdd":g("Base de polinomios alrededor de uno","Inicial",baseHints,[baseProof,r`Tomando $a=1$ se obtiene exactamente el conjunto pedido.`],r`$\{1,x-1,(x-1)^2\}$ es una base de $\mathbb R_2[x]$.`),
  "1d63f06908a8":g("Coordenadas en una base de polinomios trasladados","Intermedio",baseHints,[baseProof,r`Para la base indicada se toma $a=1$. Si $u=x-1$, entonces $x^2-x=(u+1)^2-(u+1)=u^2+u$.`],r`$S$ es base y $[x^2-x]_S=(0,1,1)^t$.`),
  "90598d462af1":g("Demostración · descomposición en función par e impar","Desafío",[r`Si una función es par e impar a la vez, compara $f(t)$ y $-f(t)$.`,r`Considera $(f(t)+f(-t))/2$ y $(f(t)-f(-t))/2$.`,r`Comprueba la paridad de cada sumando evaluándolo en $-t$.`],[r`Si $f\in W_1\cap W_2$, entonces $f(t)=f(-t)=-f(t)$, luego $2f(t)=0$ para todo $t$. Por tanto $f=0_V$ y la intersección es $\{0_V\}$.`,r`Para cualquier $f$, define $f_p(t)=(f(t)+f(-t))/2$ y $f_i(t)=(f(t)-f(-t))/2$. Se cumple $f_p(-t)=f_p(t)$, $f_i(-t)=-f_i(t)$ y $f=f_p+f_i$.`,r`La descomposición es única: la diferencia entre dos partes pares sería también impar y, por la intersección calculada, sería cero.`],r`$W_1\cap W_2=\{0_V\}$ y $f=f_p+f_i$ con las partes indicadas.`),
  "99bb1ba17d3e":g("Demostración · partes simétrica y antisimétrica","Desafío",[r`Si $A^t=A$ y $A^t=-A$, ¿qué se deduce de $2A$?`,r`Prueba con $S=(A+A^t)/2$ y $K=(A-A^t)/2$.`,r`Calcula $S^t$, $K^t$ y $S+K$.`],[r`Si $A$ pertenece a ambos subespacios, $A=A^t=-A$, así que $A=0_V$. Recíprocamente la matriz cero pertenece a ambos.`,r`Para toda matriz real cuadrada, $S=(A+A^t)/2$ satisface $S^t=S$, mientras $K=(A-A^t)/2$ satisface $K^t=-K$. Además $S+K=A$. La intersección trivial hace única esta descomposición.`],r`$W_1\cap W_2=\{0_V\}$ y $A=(A+A^t)/2+(A-A^t)/2$.`),
  "72f8065547a3":angle,
  "8917e5680648":angle,
  "7f4fc57e5dc9":functionDistance,
  "e9479b235635":functionDistance,
  "65390ff0e2c5":g("Ortogonalidad del residuo de una proyección","Inicial",orthHints,[r`Por linealidad, $\langle v-kw,w\rangle=\langle v,w\rangle-k\langle w,w\rangle$. Como $w\ne0$, $\langle w,w\rangle=\|w\|^2>0$ y al sustituir $k$ el resultado es cero.`],r`$v-kw\perp w$.`),
  "de0dd553dbfd":g("Independencia de un vector y su imagen","Desafío",[r`Parte de $\alpha x+\beta Ax=0$.`,r`Aplica $A$ a esa relación y usa $A^2x=0$.`,r`Usa primero $Ax\ne0$ y después $x\ne0$.`],[r`Aplicando $A$ a $\alpha x+\beta Ax=0$ se obtiene $\alpha Ax+\beta A^2x=\alpha Ax=0$. Como $Ax\ne0$, $\alpha=0$. La relación original queda $\beta Ax=0$, por lo que $\beta=0$.`],r`$\{x,Ax\}$ es linealmente independiente.`),
  "01d99ff5eb2f":g("Parámetro para que dos vectores sean ortogonales","Inicial",orthHints,[r`$\langle x,y\rangle=(m-1)+m(m+1)+m(m+1)=2m^2+3m-1$. Igualando a cero y resolviendo la cuadrática se obtiene $m=(-3\pm\sqrt{17})/4$.`],r`$m=(-3\pm\sqrt{17})/4$.`),
  "2361c5fac7c4":g("Combinación lineal dependiente de un parámetro","Intermedio",[r`Para que $v$ esté generado por $u,w$, el determinante con esas tres columnas debe ser cero.`,r`Calcula $u\times w$ y su producto con $v$.`,r`Completa el cuadrado en el polinomio resultante.`],[r`$u\times w=(-5k-2,11,-3-2k)$. Por tanto $v\cdot(u\times w)=-2k^2-8k-24=-2((k+2)^2+8)$, que nunca es cero para $k\in\mathbb R$. Los tres vectores son independientes para todo parámetro real.`],r`No hay valores reales de $k$ que cumplan la condición.`),
  "fc97eefba495":g("Subespacio de funciones que se anulan en dos puntos","Inicial",[r`Verifica que la función cero pertenece al conjunto.`,r`Toma dos funciones del conjunto y una combinación lineal de ellas.`,r`Evalúa esa combinación en cero y en uno.`],[r`La función cero satisface las dos condiciones. Si $f,g\in S$ y $a,b\in\mathbb R$, entonces $(af+bg)(0)=af(0)+bg(0)=0$ y análogamente $(af+bg)(1)=0$. Luego toda combinación lineal permanece en $S$, que es subespacio.`],r`$S$ es un subespacio vectorial.`),
  "7e00d326c51c":g("Subespacio definido por una ecuación propia","Inicial",[r`Reescribe $Av=\lambda v$ como $(A-\lambda I)v=0$.`,r`El conjunto solución es un núcleo.`,r`O verifica directamente estabilidad bajo combinaciones lineales.`],[r`$S=\ker(A-\lambda I)$, núcleo de una aplicación lineal. También, si $u,v\in S$, $A(au+bv)=a\lambda u+b\lambda v=\lambda(au+bv)$, y $0\in S$. No es necesario que $\lambda$ sea valor propio: en caso contrario $S=\{0\}$.`],r`$S$ es subespacio, incluso cuando solo contiene al vector cero.`),
  "817e1b3cd571":g("Base ortogonal de un plano por el origen","Inicial",orthHints,[r`De $x+y=0$ resulta $(x,y,z)=x(1,-1,0)+z(0,0,1)$. Los dos generadores son independientes. Sus normas son $\sqrt2$ y $1$, y su producto interno es cero.`],r`Una base es $\{(1,-1,0),(0,0,1)\}$: ortogonal, pero no ortonormal. Al dividir el primer vector por $\sqrt2$ se obtiene una ortonormal.`),
  "4c34761ee9b0":g("Ortogonalidad de una base bajo dos productos internos","Intermedio",orthHints,[r`1. $\int_{-1}^1x\,dx=0$, $\int_{-1}^1(x^2-1/3)\,dx=2/3-2/3=0$ y $\int_{-1}^1x(x^2-1/3)\,dx=0$ por imparidad. Los tres pares son ortogonales.`,r`2. Basta un contraejemplo: $\langle1,x\rangle=0+1+2=3\ne0$.`],"Es ortogonal para el primer producto interno, pero no para el segundo."),
  "a3c3241958d8":g("Imagen de una proyección sobre un plano","Inicial",linearHints,[r`Las primeras dos componentes de $T(x,y,z)=(x,y,0)$ son libres. Por ello la imagen es el plano generado por $(1,0,0)$ y $(0,1,0)$.`],r`$\operatorname{Im}T=\{(a,b,0):a,b\in\mathbb R\}$.`),
  "4de2d981d74f":g("Composición de transformaciones y matrices","Intermedio",matrixHints,[r`$[T\circ H]=[T][H]=\begin{pmatrix}-2&-24\\1&20\end{pmatrix}$. El orden corresponde a aplicar primero $H$.`,r`Multiplicando por $(2,3)^t$ se obtiene $(-4-72,2+60)=(-76,62)$.`],r`$M=\begin{pmatrix}-2&-24\\1&20\end{pmatrix}$ y $(T\circ H)(2,3)=(-76,62)$.`),
  "81fbcc690fdc":g("Reconstruir una transformación desde una base","Inicial",linearHints,[r`$(x,y,z)=xe_1+ye_2+ze_3$, así $T(x,y,z)=x(-1,2)+y(0,0)+z(2,1)=(-x+2z,2x+z)$. Las imágenes de la base son las columnas de la matriz.`],r`$T(x,y,z)=(-x+2z,2x+z)$ y $[T]=\begin{pmatrix}-1&0&2\\2&0&1\end{pmatrix}$.`),
  "a8a1c80a7f3c":g("Preimagen de un vector en cuatro dimensiones","Intermedio",linearHints,[r`Restando la primera ecuación de la segunda se obtiene $x=-3$. De $x+y-z=2$ resulta $y-z=5$. Las otras dos ecuaciones quedan $3x+2(y-z)=1$ y $-(y-z)=-5$, ambas verificadas.`],r`Todas las soluciones son $(x,y,z)=(-3,t+5,t)$, $t\in\mathbb R$.`),
  "e8373bf6693c":g("Evaluar una transformación mediante linealidad","Inicial",linearHints,[r`$T(3,-4,5)=3(2,3)-4(-1,4)+5(5,-3)=(35,-22)$. La matriz tiene esas tres imágenes originales como columnas.`],r`$T(3,-4,5)=(35,-22)$; $[T]=\begin{pmatrix}2&-1&5\\3&4&-3\end{pmatrix}$.`),
  "69c1f1ff963e":g("Linealidad de una aplicación sobre polinomios","Inicial",linearHints,[r`El mapa de coordenadas $a+bx+cx^2\mapsto(a,b,c)$ es lineal. Sobre esas coordenadas $F$ es multiplicación por $\begin{pmatrix}1&0&-1\\0&1&1\end{pmatrix}$, que preserva sumas y productos escalares.`],r`$F$ es lineal.`),
  "49c0ea56aa4b":g("Matriz e isomorfismo hacia un espacio de polinomios","Intermedio",linearHints,[r`Usando el orden $C=(1,x,x^2)$, las columnas son $(-1,2,5)^t,(2,3,0)^t,(4,0,0)^t$. Por tanto $[T]=\begin{pmatrix}-1&2&4\\2&3&0\\5&0&0\end{pmatrix}$.`,r`Su determinante es $-60\ne0$, por lo que la transformación es invertible y es un isomorfismo.`],r`$[T]=\begin{pmatrix}-1&2&4\\2&3&0\\5&0&0\end{pmatrix}$; sí es isomorfismo.`),
  "527dda0d9e09":g("Producto interno por evaluación en tres puntos","Desafío",[r`Simetría y bilinealidad se verifican término a término.`,r`Si la norma al cuadrado es cero, el polinomio se anula en tres puntos distintos.`,r`Un polinomio no nulo de grado a lo sumo dos no puede tener tres raíces distintas.`],[r`La forma es simétrica y bilineal, y $\langle p,p\rangle=p(0)^2+p(1)^2+p(2)^2\ge0$. Si vale cero, $p$ tiene raíces $0,1,2$, por lo que $p=0$. Es definida positiva.`,r`$\|1\|^2=3$, $\|x\|^2=5$ y $\|x^2-1/3\|^2=(-1/3)^2+(2/3)^2+(11/3)^2=14$.`],r`Es producto interno; las normas son $\sqrt3$, $\sqrt5$ y $\sqrt{14}$.`),
  "a71638d77679":g("Linealidad, núcleo y nulidad en dos dimensiones","Inicial",linearHints,[r`$T(v)=Av$ con $A=\begin{pmatrix}1&-2\\-1&1\end{pmatrix}$, así que es lineal. Resolver $x-2y=0$ y $-x+y=0$ da $x=y=0$.`],r`$T$ es lineal, $\ker T=\{(0,0)\}$ y su nulidad es $0$.`),
  "d74edbc81655":g("Imagen de una transformación con dominio real","Inicial",linearHints,[r`$T(a)=a(1+x+x^2+x^3)$, por lo que todas las imágenes son múltiplos de ese polinomio no nulo. Un solo polinomio no nulo es una base de la imagen.`],r`$\operatorname{Im}T=\operatorname{span}\{1+x+x^2+x^3\}$ y $\operatorname{rango}T=1$.`),
  "1633a2dde987":g("Matriz de una transformación en una base de llegada distinta","Intermedio",[r`Calcula $T(1,0)$ y $T(0,1)$.`,r`Expresa cada imagen como combinación de $(3,-2)$ y $(-1,1)$.`,r`Usa esas coordenadas, no las coordenadas canónicas, como columnas.`],[r`La matriz de cambio de coordenadas es $P=\begin{pmatrix}3&-1\\-2&1\end{pmatrix}$, con $P^{-1}=\begin{pmatrix}1&1\\2&3\end{pmatrix}$.`,r`$[T]_{B_1}^{B_2}=P^{-1}\begin{pmatrix}3&2\\-5&-4\end{pmatrix}=\begin{pmatrix}-2&-2\\-9&-8\end{pmatrix}$. Por ejemplo $-2(3,-2)-9(-1,1)=(3,-5)=T(1,0)$.`],r`$[T]_{B_1}^{B_2}=\begin{pmatrix}-2&-2\\-9&-8\end{pmatrix}$.`),
  "f978f5e1c7a4":g("Cuándo conmutan dos matrices con parámetros","Intermedio",matrixHints,[r`$AB=\begin{pmatrix}ab&a+b\\b^2&b+ab\end{pmatrix}$ y $BA=\begin{pmatrix}ab+b&a+b\\b^2&ab\end{pmatrix}$. La igualdad de las entradas diagonales exige $b=0$, y esa condición también es suficiente.`],r`$b=0$ y $a$ arbitrario.`),
  "699b1cbe734a":g("Sistema matricial con transpuestas","Desafío",[r`Transpone la primera ecuación para obtener $X^t+YA^t=B^t$.`,r`Réstala de la segunda y factoriza $Y$ por la izquierda.`,r`Resuelve $Y(C-A^t)=D-B^t$ y recupera $X$.`],[r`$C-A^t=\begin{pmatrix}0&-2\\1&-1\end{pmatrix}$ tiene inversa $\begin{pmatrix}-1/2&1\\-1/2&0\end{pmatrix}$.`,r`$Y=(D-B^t)(C-A^t)^{-1}=\begin{pmatrix}1/2&0\\7/2&-4\end{pmatrix}$. Luego $X=B-AY^t=\begin{pmatrix}3/2&-1/2\\3/2&7/2\end{pmatrix}$. Sustituyendo se recuperan $B$ y $D$.`],r`$X=\begin{pmatrix}3/2&-1/2\\3/2&7/2\end{pmatrix}$, $Y=\begin{pmatrix}1/2&0\\7/2&-4\end{pmatrix}$.`),
  "3430e6ac803a":g("Invertibilidad de una matriz con parámetro","Inicial",matrixHints,[r`Desarrollando por la primera fila: $\det A=-(3(k+1)+4)-(3-1)=-3k-9$. La matriz es invertible exactamente cuando este valor no es cero.`],r`$k\ne-3$.`),
  "126e057b59c7":g("Resolver una ecuación matricial con la identidad","Intermedio",matrixHints,[r`$AX=B+2I$. La inversa de $A$ es $\begin{pmatrix}1/6&0&0\\0&-5&2\\0&3&-1\end{pmatrix}$; el bloque inferior tiene determinante $-1$.`,r`Multiplicando $A^{-1}(B+2I)$ se obtiene $\begin{pmatrix}1/2&0&1/6\\-8&-15&-6\\5&9&4\end{pmatrix}$. Al multiplicar por $A$ se recupera $B+2I$.`],r`$X=\begin{pmatrix}1/2&0&1/6\\-8&-15&-6\\5&9&4\end{pmatrix}$.`),
  "f85d7d4fa0fa":g("Matriz por entradas y traza de un conmutador","Inicial",matrixHints,[r`La regla define $B=\begin{pmatrix}1&0&0\\1&2&0\\1&1&3\end{pmatrix}$.`,r`Para cualesquiera matrices cuadradas del mismo orden, $\operatorname{tr}(AB)=\sum_{i,j}a_{ij}b_{ji}=\operatorname{tr}(BA)$. Por tanto la traza de la diferencia es cero, sin necesidad de calcular todos los productos.`],r`$B=\begin{pmatrix}1&0&0\\1&2&0\\1&1&3\end{pmatrix}$ y $\operatorname{tr}(AB-BA)=0$.`),
  "f59520620f52":g("Demostración · identidad de Cayley–Hamilton en orden dos","Desafío",[r`Escribe $A=\begin{pmatrix}a&b\\c&d\end{pmatrix}$.`,r`Calcula $A^2$ y resta $(a+d)A$.`,r`Compara el resultado con $-(ad-bc)I$.`],[r`$A^2=\begin{pmatrix}a^2+bc&ab+bd\\ac+cd&bc+d^2\end{pmatrix}$. Restando $(a+d)A$ queda $\begin{pmatrix}bc-ad&0\\0&bc-ad\end{pmatrix}=-(ad-bc)I$. Como $\operatorname{tr}A=a+d$ y $\det A=ad-bc$, la identidad queda demostrada.`],r`$A^2-\operatorname{tr}(A)A+\det(A)I=0$.`),
  "bd8f2e9e97b3":g("Potencias de la matriz de unos","Intermedio",[r`Calcula $A^2$.`,r`Observa que $A^2=2A$.`,r`Prueba por inducción que $A^n=2^{n-1}A$ para $n\ge1$.`],[r`La fórmula es cierta para $n=1$. Si $A^n=2^{n-1}A$, entonces $A^{n+1}=2^{n-1}A^2=2^nA$. Esto demuestra el resultado para enteros $n\ge1$ sobre cualquier cuerpo, interpretando los escalares en él.`],r`$A^n=2^{n-1}\begin{pmatrix}1&1\\1&1\end{pmatrix}$, $n\ge1$. Para $n=0$, $A^0=I$.`),
  "e19a4d0c17b6":g("Demostración · un conmutador no puede ser la identidad","Desafío",[r`Interpreta $1$ como la identidad matricial $I_n$.`,r`Calcula la traza de $AB-BA$.`,r`Compara con $\operatorname{tr}(I_n)=n$ sobre los reales.`],[r`Si $AB-BA=I_n$, al tomar trazas se obtiene $\operatorname{tr}(AB)-\operatorname{tr}(BA)=n$. El lado izquierdo es cero por la propiedad cíclica, pero $n>0$ en $\mathbb R$. Es una contradicción.`],r`$AB-BA\ne I_n$.`),
  "2794d92c1160":g("Demostración · inversa a partir de una matriz nilpotente","Desafío",[r`Prueba con una suma geométrica finita de potencias de $A$.`,r`Multiplica $I+A+\cdots+A^{k-1}$ por $I-A$.`,r`Los términos intermedios se cancelan y queda $I-A^k$.`],[r`Sea $S=I+A+\cdots+A^{k-1}$. Entonces $(I-A)S=I-A^k=I$. También $S(I-A)=I-A^k=I$, porque $A$ conmuta con sus potencias. Por tanto $S$ es la inversa buscada.`],r`$(I-A)^{-1}=I+A+\cdots+A^{k-1}$.`),
  "d5216b5380d2":g("Potencias de una matriz de desplazamiento","Inicial",matrixHints,[r`$A$ tiene unos en la primera superdiagonal. Al multiplicar, $A^2=\begin{pmatrix}0&0&1&0\\0&0&0&1\\0&0&0&0\\0&0&0&0\end{pmatrix}$. Cada potencia desplaza los unos una superdiagonal más, así que $A^4=0$.`,r`$A$ es la matriz del enunciado y $A^{2021}=A^4A^{2017}=0$.`],r`$A$ es la matriz dada; $A^2$ tiene unos solo en $(1,3)$ y $(2,4)$; $A^{2021}=0$.`),
  "b6cb7ed19395":g("Demostración · polinomios de matrices semejantes","Desafío",[r`Escribe el polinomio como suma de monomios.`,r`Prueba $(BAB^{-1})^j=BA^jB^{-1}$ por cancelación de factores adyacentes.`,r`Usa distributividad y que los coeficientes escalares conmutan con las matrices.`],[r`Para $j=0$, $BI B^{-1}=I$. Para $j\ge1$, el producto $(BAB^{-1})^j$ cancela cada factor $B^{-1}B$ interior y queda $BA^jB^{-1}$.`,r`Si $P(t)=\sum_{j=0}^m c_jt^j$, entonces $P(BAB^{-1})=\sum c_jBA^jB^{-1}=B(\sum c_jA^j)B^{-1}=BP(A)B^{-1}$.`],r`$BP(A)B^{-1}=P(BAB^{-1})$.`),
  "e79d87e1520a":g("Linealidad · escalares, polinomios y operadores diferenciales","Intermedio",linearHints,[r`1. Para $x$ fijo, multiplicar por $x$ preserva combinaciones lineales complejas y, en particular, reales: sí en ambos casos.`,r`2. La sustitución fija $aX+b$ cumple $(\alpha P+\beta Q)(aX+b)=\alpha P(aX+b)+\beta Q(aX+b)$ y no aumenta el grado: sí.`,r`3. La diferencia $P(X+1)-P(X)$ es resta de dos operadores lineales: sí.`,r`4. No: para $v=(0,1,0)$, $F(2v)=(0,4,2)$ y $2F(v)=(0,2,2)$.`,r`5. Sí como mapa de $C^2(\mathbb R)$ a $C^0(\mathbb R)$: derivar dos veces y multiplicar por la función fija $\cos x$ son operaciones lineales. No se puede suponer que la imagen sea siempre $C^2$ sin mayor regularidad de $f$.`],"1. Sí sobre ambos cuerpos. 2. Sí. 3. Sí. 4. No. 5. Sí, con codominio de funciones continuas."),
};
