import type { IntroBlock, IntroChapter, IntroSection } from "./introductory-mathematics";

const t = String.raw;
const d = (title: string, text: string, tex?: string): IntroBlock => ({ kind: "definition", title, text, tex });
const r = (title: string, text: string, tex?: string): IntroBlock => ({ kind: "remark", title, text, tex });
const e = (title: string, text: string, tex?: string): IntroBlock => ({ kind: "example", title, text, tex });
const s = (title: string, blocks: IntroBlock[], exercise: string, hint: string, solution: string, visual?: IntroSection["visual"]): IntroSection => ({ title, blocks, exercise, hint, solution, visual });

// Lectura visual: Complejos, páginas 2–11; Forma polar y De Moivre, páginas 2–11.
// Las comprobaciones de lectura son actividades editoriales, no ejercicios atribuidos a la clase.
export const introductoryComplexNumbers: IntroChapter = {
  title: "Números complejos", slug: "complejos", sections: [
    s("Ecuaciones que nos llevan a ampliar los conjuntos", [
      d("El punto de partida de la clase", "En general nos encontramos con ecuaciones que no tienen solución en todos los conjuntos. La pregunta inicial no es cómo operar con i, sino en qué conjunto podemos resolver una ecuación."),
      e("De los enteros a los racionales", t`Si $ax+b=0$, con $a,b\in\mathbb Z$ y $a\ne0$, despejamos $ax=-b$ y luego $x=-b/a$. Este cociente pertenece a $\mathbb Q$, pero no necesariamente a $\mathbb Z$. Por eso buscar soluciones solo entre enteros puede no ser suficiente.`),
      e("De los racionales a los irracionales", t`La siguiente ecuación es $x^2=2$. La clase destaca $\sqrt2$, que es irracional: no se escribe como cociente de enteros. Precisión: la ecuación tiene las dos soluciones $x=\pm\sqrt2$. Ambas pertenecen a $\mathbb R$, pero no a $\mathbb Q$.`),
      e("Una cuadrática puede no tener solución real", t`En $ax^2+bx+c=0$, con coeficientes reales y $a\ne0$, aparece el discriminante $\Delta=b^2-4ac$. Si $\Delta<0$, la raíz de la fórmula no es real. Gráficamente, la parábola no corta el eje horizontal. Necesitamos ampliar nuevamente el conjunto de números.`, t`x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}`),
      r("Precisión sobre la primera ecuación", t`No afirmamos que $-b/a$ nunca sea entero: puede serlo. Lo que falla es que todas las ecuaciones de esa forma tengan solución en $\mathbb Z$. Esta distinción conserva la motivación sin convertirla en una afirmación falsa.`),
    ], t`Comprobación de lectura: ¿qué impide resolver una cuadrática con $\Delta<0$ dentro de $\mathbb R$?`, "Observa qué cantidad queda dentro de la raíz cuadrada.", t`El cuadrado de un real es no negativo. Por eso ningún real puede tener cuadrado $\Delta<0$, y la fórmula no produce raíces reales.`),
    s("La unidad imaginaria y el plano de Argand", [
      d("Introducir i", t`Introducimos una unidad imaginaria $i$ tal que $i^2=-1$, escrita en la clase como $i=\sqrt{-1}$. Con ella escribimos $z=a+bi$, donde a y b son reales.`, t`\mathbb C=\{a+bi=(a,b):a,b\in\mathbb R\}`),
      r("La parte imaginaria NO lleva i", t`Si $z=a+bi$, entonces $\operatorname{Re}(z)=a$ y $\operatorname{Im}(z)=b$. La parte imaginaria es el número real b, no el término bi. Esta es una de las observaciones destacadas en la clase.`),
      d("Un número, un punto y un vector", t`Representamos $z=a+bi$ mediante el punto $(a,b)$ del plano de Argand: el eje horizontal es la parte real y el vertical la imaginaria. También podemos dibujar la flecha del origen al punto. Por Pitágoras, su longitud es $|z|=\sqrt{a^2+b^2}$.`),
    ], t`Comprobación de lectura: identifica las dos partes de $z=a+bi$ y explica por qué $|z|$ es una longitud.`, "Distingue la coordenada vertical del término que contiene i.", t`$\operatorname{Re}(z)=a$ y $\operatorname{Im}(z)=b$. Las coordenadas forman un triángulo rectángulo con catetos de longitudes $|a|$ y $|b|$; la hipotenusa mide $\sqrt{a^2+b^2}$.`, "complex-plane"),
    s("Operaciones, neutros e inversos", [
      d("Suma y producto", t`Sean $z=a+bi$ y $w=c+di$. La suma se hace por componentes. En el producto, la parte real y la imaginaria se combinan así:`, t`\begin{aligned}z+w&=(a+c)+(b+d)i=(a+c,b+d),\\zw&=(ac-bd)+(ad+bc)i=(ac-bd,ad+bc).\end{aligned}`),
      d("Igualdad", t`$z=w$ si y solo si $a=c$ y $b=d$. No basta con que coincida una sola parte.`),
      d("Neutro e inverso para la suma", t`El neutro es $0=0+0i=(0,0)$. El inverso aditivo de z es $-z=-a-bi=(-a,-b)$, porque $z+(-z)=0$.`),
      d("Neutro e inverso para el producto", t`El neutro es $1=1+0i=(1,0)$. Si $z\ne0$, su inverso multiplicativo es:`, t`z^{-1}=\frac1z=\frac{a}{a^2+b^2}-\frac{b}{a^2+b^2}i`),
      r("Los complejos forman un cuerpo", t`Con estas operaciones, $\mathbb C$ es un cuerpo: suma y producto son asociativos y conmutativos, el producto distribuye sobre la suma, existen ambos neutros, todo elemento tiene inverso aditivo y todo elemento distinto de cero tiene inverso multiplicativo.`),
      d("Resta y cociente se definen usando inversos", t`$z-w=z+(-w)=(a-c)+(b-d)i$. Para $w\ne0$, $z/w=z\cdot(1/w)=z\cdot w^{-1}$. La división por cero no está definida.`),
    ], t`Comprobación de lectura: ¿por qué la fórmula de $z^{-1}$ exige $z\ne0$?`, t`Revisa cuándo $a^2+b^2$ puede valer cero.`, t`Como a y b son reales, $a^2+b^2=0$ equivale a $a=b=0$, es decir, $z=0$. Solo en ese caso se anula el denominador.`),
    s("Conjugado, módulo y la fórmula del inverso", [
      d("Dos definiciones", t`Para $z=a+bi$, definimos su conjugado $\overline z=a-bi$ y su módulo $|z|=\sqrt{a^2+b^2}$. Conjugar conserva a y cambia el signo de b.`),
      e("Por qué el producto por el conjugado es real", "Desarrollamos todos los términos; los términos imaginarios se cancelan y usamos i²=−1.", t`\begin{aligned}z\overline z&=(a+bi)(a-bi)\\&=a^2-abi+abi-b^2i^2\\&=a^2+b^2=|z|^2\in\mathbb R.\end{aligned}`),
      e("Reescribir el inverso de la sección anterior", t`Para $z\ne0$, sacamos factor común $1/(a^2+b^2)$. Así reconocemos el conjugado en el numerador y el módulo al cuadrado en el denominador.`, t`\frac a{a^2+b^2}-\frac b{a^2+b^2}i=\frac{a-bi}{a^2+b^2}=\frac{\overline z}{|z|^2}=\frac1z`),
      r("La identidad explica cómo dividir", t`Como $z\overline z=|z|^2$, multiplicar $\overline z/|z|^2$ por z da 1. Para dividir por w, usamos precisamente ese inverso: $z/w=z\overline w/|w|^2$, siempre que $w\ne0$.`),
    ], t`Comprobación de lectura: verifica que $z\,\overline z/|z|^2=1$ cuando $z\ne0$.`, "Sustituye el producto del numerador por la identidad demostrada.", t`$z\,\overline z/|z|^2=|z|^2/|z|^2=1$. La condición garantiza que no dividimos por cero.`),
    s("Distributividad y propiedades 1 a 9", [
      e("Recuperar la regla del producto", "La regla no se memoriza sin explicación: se obtiene distribuyendo y reuniendo las partes.", t`\begin{aligned}(a+bi)(c+di)&=ac+adi+cbi+bdi^2\\&=ac+(ad+cb)i-bd\\&=(ac-bd)+(ad+cb)i.\end{aligned}`),
      d("Multiplicar por un real", t`Para $\alpha\in\mathbb R$, $\alpha(a+bi)=\alpha a+\alpha bi$. En coordenadas, $\alpha(a,b)=(\alpha a,\alpha b)$. A continuación, z y w son complejos; k, α y β son reales.`),
      d("1–4. Propiedades del conjugado", t`1. Conjugar dos veces devuelve z. 2. Un factor real puede salir del conjugado. 3. El conjugado de una suma es la suma de conjugados. 4. Lo mismo ocurre con productos y cocientes; en el cociente, $w\ne0$.`, t`\begin{aligned}\overline{\overline z}&=z,&\overline{kz}&=k\overline z,\\\overline{z+w}&=\overline z+\overline w,&\overline{zw}&=\overline z\,\overline w,\\\overline{z/w}&=\overline z/\overline w.\end{aligned}`),
      d("5–8. Propiedades de la multiplicación por reales", "Podemos asociar los factores reales y distribuir respecto de ambas sumas. El real 1 no cambia el complejo.", t`\begin{aligned}5.\quad\alpha(\beta z)&=(\alpha\beta)z=\beta(\alpha z),\\6.\quad(\alpha+\beta)z&=\alpha z+\beta z,\\7.\quad\alpha(z+w)&=\alpha z+\alpha w,\\8.\quad1z&=z.\end{aligned}`),
      d("9. Positividad del módulo", t`$|z|\ge0$ y $|z|=0$ si y solo si $z=0+0i$. El módulo no es una coordenada con signo: es una distancia.`),
    ], t`Comprobación de lectura: verifica $\overline{\overline z}=z$ usando $z=a+bi$.`, "Cambia dos veces el signo de la parte imaginaria.", t`$\overline{\overline{a+bi}}=\overline{a-bi}=a+bi=z$.`),
    s("Propiedades 10 a 15: módulo y valor absoluto", [
      d("10. Módulo de un múltiplo real", t`$|\alpha z|=|\alpha|\,|z|$. Las barras de α indican valor absoluto de un real; las de z indican módulo de un complejo.`),
      r("Un real puro: ambas nociones coinciden", t`Si $z=a+0i$, entonces $|z|=\sqrt{a^2+0^2}=\sqrt{a^2}=|a|$. Atención: $\sqrt{a^2}$ es $|a|$, no necesariamente a.`),
      d("11–13. Simetrías, productos y cocientes", t`11. $|z|=|-z|=|\overline z|$. 12. $|zw|=|z||w|$. 13. $|z/w|=|z|/|w|$ para $w\ne0$. Negar y conjugar cambian la posición, pero no la distancia al origen.`),
      d("14. Las componentes no superan al módulo", t`$|\operatorname{Re}(z)|\le|z|$ y $|\operatorname{Im}(z)|\le|z|$. En el triángulo rectángulo, ningún cateto es más largo que la hipotenusa.`),
      d("15. Desigualdad triangular", t`$|z+w|\le|z|+|w|$. Llegar directamente al extremo de z+w no requiere más distancia que recorrer primero z y luego w.`),
    ], t`Comprobación de lectura: ¿por qué negar o conjugar z no cambia su módulo?`, "Escribe las coordenadas y observa sus cuadrados.", t`Los tres módulos son $\sqrt{a^2+b^2}$: $(-a)^2=a^2$ y $(-b)^2=b^2$.`),
    s("Leer las operaciones en el plano", [
      d("Los dos vectores básicos", t`$z=(a,b)=a(1,0)+b(0,1)$. El vector $(1,0)$ representa 1; $(0,1)$ representa i. Así, $a+bi$ también describe cómo construir el vector a partir de los ejes.`),
      d("Escalar, negar y conjugar", t`$2z=(2a,2b)$ duplica la longitud y $z/2=(a/2,b/2)$ la reduce a la mitad. $-z=(-a,-b)$ apunta en sentido opuesto. En cambio, $\overline z=(a,-b)$ es el reflejo respecto del eje real: no debe confundirse con −z.`),
      d("La suma es la diagonal de un paralelogramo", t`Para dibujar z+w, trasladamos el vector w al extremo de z, sin girarlo ni cambiar su longitud. La flecha desde el origen hasta el extremo final es z+w.`),
      e("Los puntos dibujados en la clase", t`$z_1=-2+3i$ queda en el segundo cuadrante; $z_2=4+4i$, en el primero; $z_3=2-i$, en el cuarto. Su conjugado $\overline{z_3}=2+i$ queda encima del eje real, a la misma distancia de él.`),
    ], t`Comprobación de lectura: compara $-z_3$ con $\overline{z_3}$ para $z_3=2-i$.`, "Negar cambia ambas coordenadas; conjugar cambia solo la segunda.", t`$-z_3=-2+i$, mientras que $\overline{z_3}=2+i$. Son puntos distintos, aunque ambos tienen módulo $\sqrt5$.`, "complex-geometry"),
    s("De la forma algebraica a la forma polar", [
      d("Deducir la representación desde el triángulo", t`Para $z\ne0$, sea α un ángulo medido desde el eje real positivo. La forma $a+bi$ se llama algebraica o canónica; $(a,b)$ da las coordenadas cartesianas. Como $\cos\alpha=a/|z|$ y $\sin\alpha=b/|z|$, obtenemos:`, t`\begin{aligned}a&=|z|\cos\alpha,&b&=|z|\sin\alpha,\\z&=|z|\cos\alpha+i|z|\sin\alpha\\&=|z|(\cos\alpha+i\sin\alpha)=|z|\operatorname{cis}\alpha.\end{aligned}`),
      r("La i se conserva", t`Definimos $\operatorname{cis}\alpha=\cos\alpha+i\sin\alpha$. La i junto al seno es indispensable: omitirla convertiría la expresión en un número real. Esta precisión corrige la omisión en el cierre del primer desarrollo.`),
      d("Argumento y cuadrantes", t`Elegimos $\alpha=\operatorname{Arg}(z)\in[0,2\pi)$. Los signos de (a,b) ubican el cuadrante: (+,+) primero; (−,+) segundo; (−,−) tercero; (+,−) cuarto. Los ángulos que difieren en $2k\pi$ representan la misma dirección. El cero no tiene argumento definido.`),
      r("Precisión sobre arctan", t`Si $a\ne0$, $\tan\alpha=b/a$, pero $\arctan(b/a)$ devuelve un ángulo en $(-\pi/2,\pi/2)$, no en $[0,2\pi)$. Hay que ajustarlo según el cuadrante. Si $a=0$, no dividimos por cero: leemos el eje imaginario directamente.`),
      e("El ejercicio que la clase deja para ustedes", t`Para $z=-3+\sqrt3i$, tenemos $a=-3<0$ y $b=\sqrt3>0$. Está en el segundo cuadrante. La clase pide encontrar α: usa $\tan\alpha=-\sqrt3/3$ y no olvides el cuadrante.`),
    ], t`Ejercicio de la clase: encuentra el argumento en $[0,2\pi)$ y la forma polar de $z=-3+\sqrt3i$.`, t`El ángulo de referencia es $\pi/6$. En el segundo cuadrante se resta ese ángulo a π.`, t`$|z|=\sqrt{9+3}=2\sqrt3$. El argumento es $\pi-\pi/6=5\pi/6$. Así, $z=2\sqrt3\operatorname{cis}(5\pi/6)$.`),
    s("Por qué usar forma polar: productos y potencias", [
      d("Multiplicaciones y divisiones más sencillas", t`Sean $z_1=r_1\operatorname{cis}\alpha_1$ y $z_2=r_2\operatorname{cis}\alpha_2$. Al multiplicar, multiplicamos módulos y sumamos ángulos. Al dividir, dividimos módulos y restamos ángulos; exigimos $z_2\ne0$.`, t`z_1z_2=r_1r_2\operatorname{cis}(\alpha_1+\alpha_2),\qquad\frac{z_1}{z_2}=\frac{r_1}{r_2}\operatorname{cis}(\alpha_1-\alpha_2)`),
      e("Primero, el cuadrado", t`Sea $z=r\operatorname{cis}\alpha$. Al multiplicarlo por sí mismo se obtiene $z^2=(r\operatorname{cis}\alpha)(r\operatorname{cis}\alpha)=r^2\operatorname{cis}(2\alpha)$.`),
      e("El paso inductivo de la clase", t`La fórmula es inmediata para n=1. Supongamos $z^{n-1}=r^{n-1}\operatorname{cis}((n-1)\alpha)$. Entonces:`, t`\begin{aligned}z^n&=z^{n-1}z\\&=[r^{n-1}\operatorname{cis}((n-1)\alpha)][r\operatorname{cis}\alpha]\\&=r^{n-1+1}\operatorname{cis}((n-1)\alpha+\alpha)\\&=r^n\operatorname{cis}(n\alpha).\end{aligned}`),
      d("Teorema de De Moivre", t`Para n entero positivo, $z^n=|z|^n\operatorname{cis}(n\alpha)$. Se eleva el módulo y se multiplica el ángulo: no se elevan por separado el seno y el coseno.`),
      e("El ejemplo de la clase, con sus pasos", t`Calcula $z^3$ para $z=4(\cos(5\pi/12)+i\sin(5\pi/12))$. El nuevo ángulo es $3(5\pi/12)=5\pi/4=\pi+\pi/4$, en el tercer cuadrante. Allí tanto seno como coseno son negativos.`, t`\begin{aligned}z^3&=4^3\operatorname{cis}(3\cdot5\pi/12)\\&=64\operatorname{cis}(5\pi/4)\\&=64\left(-\frac{\sqrt2}{2}-i\frac{\sqrt2}{2}\right)\\&=-32\sqrt2-32\sqrt2\,i.\end{aligned}`),
      d("Los valores notables usados en el cálculo", "La tabla de la clase permite recuperar los valores y luego ajustar los signos al cuadrante.", t`\begin{array}{c|ccccc}\text{grados}&0&30&45&60&90\\\hline\cos&1&\sqrt3/2&\sqrt2/2&1/2&0\\\sin&0&1/2&\sqrt2/2&\sqrt3/2&1\end{array}`),
    ], t`Comprobación de lectura: ¿por qué las dos componentes de $z^3$ en el ejemplo son negativas?`, t`Ubica $5\pi/4=225^\circ$ en el plano.`, "El ángulo está en el tercer cuadrante, donde las coordenadas horizontal y vertical son negativas. Por eso coseno y seno valen −√2/2."),
    s("Deducir las raíces y encontrar las raíces cúbicas de i", [
      d("Plantear la ecuación antes de usar la fórmula", t`Sea $z=r\operatorname{cis}\alpha\ne0$ y n natural positivo. Buscamos $w=\rho\operatorname{cis}\beta$ tal que $w^n=z$. Por De Moivre, $\rho^n\operatorname{cis}(n\beta)=r\operatorname{cis}\alpha$. Igualamos módulos y direcciones, recordando las vueltas completas.`),
      e("Separar módulo y ángulo", t`De $\rho^n=r$ sale $\rho=\sqrt[n]r$. De $n\beta=\alpha+2k\pi$, con $k\in\mathbb Z$, sale $\beta=(\alpha+2k\pi)/n$. Para obtener las n raíces distintas basta tomar k desde 0 hasta n−1.`, t`w_k=\sqrt[n]r\operatorname{cis}\left(\frac{\alpha+2k\pi}{n}\right),\qquad k=0,\ldots,n-1`),
      e("Ejemplo de clase: raíces cúbicas de i", t`$i=0+1i$ tiene módulo $\sqrt{0^2+1^2}=1$ y argumento $\pi/2$, porque está en el eje imaginario positivo. Precisión: no calculamos $\arctan(1/0)$; esa división no existe. Sustituimos n=3 y α=π/2:`, t`\begin{aligned}w_0&=\operatorname{cis}\left(\frac{\pi/2+0}{3}\right)=\operatorname{cis}(\pi/6)=\frac{\sqrt3}{2}+\frac12i,\\w_1&=\operatorname{cis}\left(\frac{\pi/2+2\pi}{3}\right)=\operatorname{cis}(5\pi/6)=-\frac{\sqrt3}{2}+\frac12i,\\w_2&=\operatorname{cis}\left(\frac{\pi/2+4\pi}{3}\right)=\operatorname{cis}(3\pi/2)=-i.\end{aligned}`),
      r("La observación geométrica", t`Las tres raíces tienen módulo 1 y están separadas por $2\pi/3=360^\circ/3=120^\circ$: forman un triángulo equilátero. En general, para $z\ne0$ y $n\ge3$, las raíces forman un polígono regular de n lados. Con n=2 son dos puntos opuestos y con n=1 hay un solo punto. Si z=0, la única raíz es 0.`),
    ], t`Comprobación de lectura: verifica que la tercera raíz $w_2=-i$ cumple $w_2^3=i$.`, t`Usa $i^2=-1$ para calcular primero $(-i)^2$.`, t`$(-i)^2=-1$ y $(-i)^3=(-1)(-i)=i$. Los otros dos argumentos, al triplicarse, dan $\pi/2$ y $5\pi/2$, la misma dirección de i.`, "complex-roots"),
    s("Conjugado en polar, exponencial y conversión de ángulos", [
      d("Reflejar cambia el ángulo, no el módulo", t`Si $z=a+bi=r\operatorname{cis}\alpha$, entonces $\overline z=a-bi$. Sus módulos coinciden porque $a^2+(-b)^2=a^2+b^2$. El reflejo tiene ángulo −α; escrito en $[0,2\pi)$, es $2\pi-\alpha$ cuando $\alpha\ne0$. Si $\alpha=0$, el argumento sigue siendo 0.`),
      r("La observación final: notación exponencial", t`La identidad de Euler permite escribir $\operatorname{cis}\alpha=\cos\alpha+i\sin\alpha=e^{i\alpha}$. Así, la forma exponencial es $z=|z|e^{i\alpha}$. Es el mismo número, expresado con otra notación.`),
      d("De grados a radianes y de radianes a grados", t`Como $180^\circ=\pi$ radianes, un ángulo de D grados equivale a $D\pi/180$ radianes. Un ángulo de R radianes equivale a $180R/\pi$ grados. Por ejemplo, $\pi/6$ radianes son $(\pi/6)(180/\pi)=30^\circ$.`),
    ], t`Comprobación de lectura: expresa el conjugado de $r\operatorname{cis}\alpha$ en notación exponencial.`, "El reflejo respecto del eje real cambia el signo del ángulo.", t`$\overline z=re^{-i\alpha}$. Para $0<\alpha<2\pi$, también $\overline z=re^{i(2\pi-\alpha)}$.`),
  ],
};
