// Referencias internas de edición: no se muestran ni enlazan documentos al lector.
// Cada desarrollo se contrasta visualmente con las páginas indicadas.
export type SourceDevelopment = { title: string; source: string; pages: [number, number]; steps: string[] };
const t = String.raw;
export const sourceDevelopments: Record<string, SourceDevelopment[]> = {
  "trigonometria-3": [
    { title: "Deducir las fórmulas de diferencia y ángulo doble", source: "F.-Trigonometrica-comentarios-.pdf", pages: [52,59], steps: [
      t`Partimos de $\sin(\alpha+\beta)=\sin\alpha\cos\beta+\cos\alpha\sin\beta$. Para la diferencia, sustituimos β por −β y usamos que el coseno es par y el seno impar. Resulta $\sin(\alpha-\beta)=\sin\alpha\cos\beta-\cos\alpha\sin\beta$.`,
      t`De $\cos(\alpha+\beta)=\cos\alpha\cos\beta-\sin\alpha\sin\beta$ se obtiene de igual modo $\cos(\alpha-\beta)=\cos\alpha\cos\beta+\sin\alpha\sin\beta$.`,
      t`La tangente de la suma es el cociente del seno y el coseno de la suma. Dividimos numerador y denominador por $\cos\alpha\cos\beta$: $\tan(\alpha+\beta)=(\tan\alpha+\tan\beta)/(1-\tan\alpha\tan\beta)$. Se exige que todas las tangentes y el cociente estén definidos.`,
      t`Como $\tan(-\beta)=\sin(-\beta)/\cos(-\beta)=-\tan\beta$, sustituir −β da $\tan(\alpha-\beta)=(\tan\alpha-\tan\beta)/(1+\tan\alpha\tan\beta)$, en su dominio.`,
      t`Al poner $\beta=\alpha$ en la fórmula del seno: $\sin(2\alpha)=\sin\alpha\cos\alpha+\cos\alpha\sin\alpha=2\sin\alpha\cos\alpha$.`,
      t`Para el coseno: $\cos(2\alpha)=\cos^2\alpha-\sin^2\alpha$. Sustituir $\cos^2\alpha=1-\sin^2\alpha$ da $1-2\sin^2\alpha$; sustituir $\sin^2\alpha=1-\cos^2\alpha$ da $2\cos^2\alpha-1$.`,
      t`Un ángulo complementario también se obtiene con la diferencia: $\sin(\pi/2-\alpha)=\sin(\pi/2)\cos\alpha-\cos(\pi/2)\sin\alpha=\cos\alpha$. En un triángulo rectángulo se intercambian el cateto opuesto y el adyacente.`,
    ] },
    { title: "Prostaféresis: transformar productos en sumas y volver", source: "F.-Trigonometrica-comentarios-.pdf", pages: [60,63], steps: [
      t`Sumamos las identidades de $\sin(x+y)$ y $\sin(x-y)$. Los términos $\cos x\sin y$ se cancelan y queda $\sin(x+y)+\sin(x-y)=2\sin x\cos y$.`,
      t`Dividir por 2 da $\sin x\cos y=[\sin(x+y)+\sin(x-y)]/2$. Restar las mismas identidades da $\cos x\sin y=[\sin(x+y)-\sin(x-y)]/2$.`,
      t`Sumando y restando las fórmulas del coseno se obtiene $\cos x\cos y=[\cos(x+y)+\cos(x-y)]/2$ y $\sin x\sin y=[\cos(x-y)-\cos(x+y)]/2$.`,
      t`Para invertir el procedimiento, definimos $u=x+y$ y $v=x-y$. Sumar y restar estas ecuaciones da $x=(u+v)/2$ y $y=(u-v)/2$.`,
      t`Sustituimos en la primera fórmula: $\sin u+\sin v=2\sin((u+v)/2)\cos((u-v)/2)$. Del mismo modo, $\sin u-\sin v=2\cos((u+v)/2)\sin((u-v)/2)$.`,
      t`Para el coseno: $\cos u+\cos v=2\cos((u+v)/2)\cos((u-v)/2)$ y $\cos u-\cos v=-2\sin((u+v)/2)\sin((u-v)/2)$. El signo menos de la última fórmula es indispensable.`,
      t`La aplicación numérica usa $\cos84^\circ\cos44^\circ=[\cos128^\circ+\cos40^\circ]/2\approx0.07519$. Aproximar $0.105\cdot0.720$ de este modo da cerca de 0.075, pero no es una igualdad exacta: $105\cdot720=75600$. Las aproximaciones angulares introducen error.`,
    ] },
    { title: "Construir un período de la gráfica, punto por punto", source: "F.-Trigonometrica-comentarios-.pdf", pages: [96,103], steps: [
      t`Para $A\sin(Bx+C)+D$, con $A,B\ne0$, un ciclo corresponde a una variación de $2\pi$ en el argumento. Si $B>0$, $0\le Bx+C\le2\pi$ da $-C/B\le x\le(2\pi-C)/B$. La longitud de ese intervalo es $2\pi/B$. En general, el período positivo es $2\pi/|B|$.`,
      t`En $f(x)=2\sin(3x)-1$, tomamos argumentos $0,\pi/2,\pi,3\pi/2,2\pi$. Dividir por 3 da las entradas $0,\pi/6,\pi/3,\pi/2,2\pi/3$.`,
      t`Los senos correspondientes son 0,1,0,−1,0. Multiplicar por 2 y restar 1 da los puntos $(0,-1)$, $(\pi/6,1)$, $(\pi/3,-1)$, $(\pi/2,-3)$ y $(2\pi/3,-1)$. El recorrido es $[-3,1]$ y el período $2\pi/3$.`,
      t`Para $g(x)=-3\sin(2x-\pi/2)+1$, primero factorizamos el argumento: $2(x-\pi/4)$. El desplazamiento horizontal es $\pi/4$ a la derecha, no $\pi/2$.`,
      t`Igualar el argumento a $0,\pi/2,\pi,3\pi/2,2\pi$ da $x=\pi/4,\pi/2,3\pi/4,\pi,5\pi/4$. Las imágenes son 1,−2,1,4,1. Con estos cinco puntos se traza un período y luego se repite.`,
      t`El signo negativo refleja verticalmente la onda. Para el recorrido, partimos de $-1\le\sin(2x-\pi/2)\le1$; multiplicar por −3 invierte las desigualdades: $3\ge-3\sin(2x-\pi/2)\ge-3$. Sumar 1 da $4\ge g(x)\ge-2$. Amplitud 3, período π y recorrido $[-2,4]$.`,
    ] },
  ],
  "logica-2": [
    { title: "Las equivalencias que permiten transformar una proposición", source: "Logica.pdf", pages: [27,34], steps: [
      t`Dos expresiones son lógicamente equivalentes si coinciden en toda asignación de valores de verdad. Escribimos $P\equiv Q$; equivalentemente, $P\leftrightarrow Q$ es una tautología.`,
      t`Idempotencia: $p\lor p\equiv p$ y $p\land p\equiv p$. Conmutatividad: $p\lor q\equiv q\lor p$ y $p\land q\equiv q\land p$. Asociatividad: $(p\lor q)\lor r\equiv p\lor(q\lor r)$ y $(p\land q)\land r\equiv p\land(q\land r)$.`,
      t`Distributividad: $p\lor(q\land r)\equiv(p\lor q)\land(p\lor r)$ y $p\land(q\lor r)\equiv(p\land q)\lor(p\land r)$. Las dos operaciones tienen una ley distributiva.`,
      t`Con V verdadero y F falso: $p\lor F\equiv p$, $p\land V\equiv p$, $p\lor V\equiv V$ y $p\land F\equiv F$. Además, $\neg\neg p\equiv p$, $p\lor\neg p\equiv V$ y $p\land\neg p\equiv F$.`,
      t`De Morgan: $\neg(p\lor q)\equiv\neg p\land\neg q$ y $\neg(p\land q)\equiv\neg p\lor\neg q$. Absorción: $(p\lor q)\land p\equiv p$ y $(p\land q)\lor p\equiv p$.`,
      t`El condicional equivale a $\neg p\lor q$. El bicondicional exige las dos direcciones: $(p\to q)\land(q\to p)$. La contrarrecíproca $\neg q\to\neg p$ es equivalente a $p\to q$; la recíproca no tiene por qué serlo.`,
      t`Para desarrollar $p\leftrightarrow q$, sustituimos ambas implicaciones: $(\neg p\lor q)\land(\neg q\lor p)$. Distribuir da $(\neg p\land\neg q)\lor(q\land\neg q)\lor(\neg p\land p)\lor(q\land p)$.`,
      t`Los dos términos centrales son F. Al eliminarlos y conmutar el último: $p\leftrightarrow q\equiv(\neg p\land\neg q)\lor(p\land q)$. Esto expresa que ambas proposiciones son falsas o ambas verdaderas.`,
      t`La transitividad afirma $[(p\to q)\land(q\to r)]\to(p\to r)$. Si las dos premisas son verdaderas y p ocurre, se obtiene q y después r; si las premisas no son ambas verdaderas, el condicional exterior es verdadero. Por eso es una tautología.`,
    ] },
  ],
  "logica-3": [
    { title: "El orden de los cuantificadores cambia lo que hay que demostrar", source: "Logica.pdf", pages: [43,48], steps: [
      t`Sea $A=\{1,2,3,4\}$. La afirmación $\forall x\in A\;(x+3<6)$ es falsa: x=3 es un contraejemplo. Para $\exists x\in A\;(2x^2+x=15)$, los cuatro valores son 3, 10, 21 y 36; ninguno es 15, por lo que también es falsa.`,
      t`$\forall x\in A\;\forall y\in A\;(x^2+y\text{ es par})$ es falsa: con x=1 e y=2 obtenemos 3. Un solo par basta para refutar los dos cuantificadores universales.`,
      t`$\exists x\in A\;\forall y\in A\;(x^2+y\text{ es par})$ también es falsa. Cualquiera sea el x fijo, al sumar y=1 e y=2 se obtienen números consecutivos: no pueden ser ambos pares.`,
      t`En cambio, $\forall y\in A\;\exists x\in A\;(x^2+y\text{ es par})$ es verdadera. Si y es impar elegimos x=1; si y es par elegimos x=2. Ahora x puede depender de y.`,
      t`Para negar $\forall x\in A\;(x>1\to x=2)$, cambiamos el cuantificador y negamos la implicación. Como $\neg(P\to Q)\equiv P\land\neg Q$, resulta $\exists x\in A\;(x>1\land x\ne2)$.`,
      t`Negar $\forall x\in A\;\exists y\in A\;(y>x)$ da $\exists x\in A\;\forall y\in A\;(y\le x)$. El orden se mantiene; cambia cada cuantificador y se niega la desigualdad.`,
      t`Negar $\exists x\in A\;\forall y\in A\;(x\le y)$ da $\forall x\in A\;\exists y\in A\;(x>y)$. Negar «menor o igual» produce «mayor», no «mayor o igual».`,
      t`Para $\exists x\in A\;\forall y\in A\;(p(x,y)\leftrightarrow q(y))$, la negación es $\forall x\in A\;\exists y\in A\;[(p(x,y)\land\neg q(y))\lor(q(y)\land\neg p(x,y))]$. Un bicondicional es falso cuando los dos lados difieren.`,
    ] },
  ],
  "vectores-4": [
    { title: "Deducir y calcular los tres ángulos directores", source: "Vectores-comentarios.pdf", pages: [49,56], steps: [
      t`Para $v=(a,b,c)\ne(0,0,0)$ usamos los vectores unitarios $i=(1,0,0)$, $j=(0,1,0)$ y $k=(0,0,1)$. Los ángulos directores α, β y γ se miden con los ejes positivos y pertenecen a $[0,\pi]$.`,
      t`Por la fórmula del producto punto, $\cos\alpha=(v\cdot i)/(\|v\|\|i\|)=a/\|v\|$, porque $v\cdot i=a$ y $\|i\|=1$. Del mismo modo, $\cos\beta=b/\|v\|$ y $\cos\gamma=c/\|v\|$.`,
      t`En el ejemplo $v=i+2j+3k=(1,2,3)$, calculamos primero $\|v\|=\sqrt{1^2+2^2+3^2}=\sqrt{14}$.`,
      t`Entonces $\alpha=\arccos(1/\sqrt{14})$, $\beta=\arccos(2/\sqrt{14})$ y $\gamma=\arccos(3/\sqrt{14})$. En grados son aproximadamente $74.50^\circ$, $57.69^\circ$ y $36.70^\circ$. No son los ángulos de un triángulo y no tienen que sumar 180°.`,
      t`Dividir por la norma produce $v/\|v\|=(\cos\alpha,\cos\beta,\cos\gamma)$. Como su norma es 1, al cuadrar se obtiene $\cos^2\alpha+\cos^2\beta+\cos^2\gamma=1$. En el ejemplo: $(1+4+9)/14=1$.`,
      t`Los tres ángulos fijan la dirección, pero no la longitud. Para reconstruir el vector hace falta también su norma: $v=\|v\|(\cos\alpha,\cos\beta,\cos\gamma)$.`,
    ] },
  ],
  "ecuaciones-2": [
    { title: "Dos valores absolutos anidados: conservar los cuatro casos", source: "Ecuaciones_1.pdf", pages: [43,45], steps: [
      t`Resolvemos $||x+1|-2|=1$. El signo de $|x+1|-2$ determina cómo abrir las barras exteriores; el de $x+1$ determina cómo abrir las interiores.`,
      t`Primer caso: $|x+1|-2\ge0$, es decir, $x\le-3$ o $x\ge1$. Si además $x+1\ge0$, queda $x+1-2=1$, de donde $x=2$. Cumple las dos condiciones.`,
      t`En el mismo caso exterior, si $x+1<0$, queda $-(x+1)-2=1$. Así, $-x-3=1$ y $x=-4$, que también cumple las condiciones.`,
      t`Segundo caso: $|x+1|-2<0$, equivalente a $-3<x<1$. Abrimos las barras exteriores cambiando el signo: $-(|x+1|-2)=1$.`,
      t`Si $x\ge-1$, resulta $-(x+1-2)=1$, luego $-x+1=1$ y $x=0$. Si $x<-1$, resulta $-(-(x+1)-2)=1$, luego $x+3=1$ y $x=-2$. Cada valor pertenece a su intervalo.`,
      t`El conjunto solución es $\{-4,-2,0,2\}$. Como comprobación, los valores interiores $|x+1|$ son 3 o 1, y en ambos casos $||x+1|-2|=1$.`,
    ] },
  ],
  "funciones-2": [
    { title: "Funciones por tramos: elegir la fórmula antes de evaluar", source: "funciones-comentarios.pdf", pages: [47,50], steps: [
      t`Consideramos $f(x)=x$ para $x<-2$, $f(x)=4-x^2$ para $-2\le x\le2$ y $f(x)=2+x$ para $x>2$. No son tres valores para una misma entrada: cada intervalo selecciona una sola regla.`,
      t`Como $-3<-2$, $f(-3)=-3$. En cambio, −2 pertenece al tramo central: $f(-2)=4-(-2)^2=0$. El extremo del primer tramo en $(-2,-2)$ queda abierto y el punto $(-2,0)$ queda cerrado.`,
      t`También $f(0)=4$, $f(2)=0$ y $f(3)=5$. En x=2, la parábola incluye $(2,0)$; el tramo derecho no incluye $(2,4)$.`,
      t`El dominio es todo $\mathbb R$. Los recorridos de los tres tramos son $(-\infty,-2)$, $[0,4]$ y $(4,\infty)$, por lo que el recorrido total es $(-\infty,-2)\cup[0,\infty)$.`,
      t`Para el segundo ejemplo, $g(x)=4x+3$ en $[-2,0)$, $g(x)=1+x^2$ en $[0,2]$ y $g(x)=7$ en $(2,\infty)$. Su dominio es $[-2,\infty)$: $g(-3)$ no existe; $g(0)=1$, $g(2)=5$ y $g(3)=7$.`,
      t`Los recorridos parciales son $[-5,3)$, $[1,5]$ y $\{7\}$; su unión es $[-5,5]\cup\{7\}$. Los cortes con los ejes son $(-3/4,0)$ y $(0,1)$. Resolver una fórmula fuera de su tramo no aporta puntos a la gráfica.`,
    ] },
  ],
  "funciones-3": [
    { title: "Operaciones y composición: dos controles distintos del dominio", source: "funciones-comentarios.pdf", pages: [52,55], steps: [
      t`Sean $f(x)=1/(x-2)$ y $g(x)=\sqrt x$. Para sumar, restar o multiplicar necesitamos que ambas existan: $x\ge0$ y $x\ne2$. El dominio común es $[0,2)\cup(2,\infty)$.`,
      t`Las reglas son $(f+g)(x)=1/(x-2)+\sqrt x$, $(f-g)(x)=1/(x-2)-\sqrt x$ y $(fg)(x)=\sqrt x/(x-2)$. En x=4 valen, respectivamente, $5/2$, $-3/2$ y 1.`,
      t`En $(f/g)(x)=1/[(x-2)\sqrt x]$ se agrega $g(x)\ne0$. El dominio es $(0,2)\cup(2,\infty)$ y $(f/g)(4)=1/4$.`,
      t`Ahora sean $f(x)=\sqrt x$ y $g(x)=\sqrt{2-x}$. Para $(g\circ f)(x)=\sqrt{2-\sqrt x}$ exigimos primero $x\ge0$ y después $\sqrt x\le2$: el dominio es $[0,4]$.`,
      t`En $(f\circ g)(x)=\sqrt{\sqrt{2-x}}$, basta $x\le2$: la raíz interior ya es no negativa. El dominio es $(-\infty,2]$. El orden de composición cambió la regla y el dominio.`,
      t`Por último, $(f\circ f)(x)=\sqrt{\sqrt x}$ tiene dominio $[0,\infty)$. Para $(g\circ g)(x)=\sqrt{2-\sqrt{2-x}}$ necesitamos $x\le2$ y $2-x\le4$, de donde $-2\le x\le2$.`,
    ] },
    { title: "Encontrar una inversa y comprobar las dos composiciones", source: "funciones-comentarios.pdf", pages: [60,65], steps: [
      t`La función $x^2-4$ en $[-2,\infty)$ no es inyectiva: −1 y 1 están en el dominio y tienen la misma imagen −3. No podemos definir una inversa única en todo ese dominio.`,
      t`Para $f(x)=(x-3)/2$, escribimos $y=(x-3)/2$, multiplicamos por 2 y despejamos: $x=2y+3$. Así, $f^{-1}(x)=2x+3$. Ambas composiciones devuelven x.`,
      t`Consideremos ahora $f(x)=\sqrt{x-2}+1$. Su dominio es $[2,\infty)$ y su recorrido $[1,\infty)$. Como la raíz es estrictamente creciente, cada imagen corresponde a una sola entrada.`,
      t`De $y=\sqrt{x-2}+1$ obtenemos $y-1=\sqrt{x-2}$. Sabemos $y\ge1$ antes de elevar al cuadrado: $(y-1)^2=x-2$, luego $f^{-1}(y)=(y-1)^2+2$.`,
      t`La inversa tiene dominio $[1,\infty)$ y recorrido $[2,\infty)$. Para $x\ge2$, $f^{-1}(f(x))=(\sqrt{x-2})^2+2=x$. Para $x\ge1$, $f(f^{-1}(x))=\sqrt{(x-1)^2}+1=|x-1|+1=x$. La última igualdad usa el dominio.`,
      t`Sus gráficas se reflejan respecto de $y=x$. En la conversión $F(C)=9C/5+32$, la inversa es $F^{-1}(F)=5(F-32)/9$: convierte Fahrenheit a Celsius. En particular, $F^{-1}(86)=30$.`,
    ] },
  ],
  "funciones-4": [
    { title: "Logaritmos: gráfica, inversa y modelos", source: "funciones-comentarios.pdf", pages: [75,77], steps: [
      t`Para $f(x)=\log_2x-1$, el dominio es $(0,\infty)$ y el recorrido es $\mathbb R$. Es creciente y no corta el eje vertical porque x=0 no pertenece al dominio.`,
      t`El corte horizontal satisface $\log_2x-1=0$, así que $x=2$. Para la inversa: $y+1=\log_2x$ equivale a $x=2^{y+1}$. Por tanto $f^{-1}(x)=2^{x+1}$, de dominio real y recorrido positivo.`,
      t`Comprobamos $f(f^{-1}(x))=\log_2(2^{x+1})-1=x$ para todo real. En el otro orden, $f^{-1}(f(x))=2^{\log_2x}=x$, con $x>0$.`,
      t`En el modelo de población, medimos t en años desde 1997 e y en millones: $y(t)=12e^{kt}$. El dato de 2007 da $16=12e^{10k}$, luego $k=\ln(4/3)/10$. Para 2012, $t=15$ y $y(15)=12(4/3)^{3/2}\approx18.48$ millones. Es una estimación del modelo, no un dato observado.`,
      t`En el modelo de magnitud estelar $m=6-2.5\log_{10}(L/L_0)$, con $L,L_0>0$, tomar $L=10^{0.4}L_0$ da $m=6-2.5(0.4)=5$.`,
      t`Para despejar el flujo, $\log_{10}(L/L_0)=(6-m)/2.5=2.4-0.4m$. Luego $L=L_0\,10^{2.4-0.4m}$. El término constante del exponente es 2.4: se obtiene dividiendo 6 por 2.5.`,
    ] },
  ],
  "progresiones-binomio-1": [
    { title: "Reconocer la diferencia y reconstruir una progresión", source: "Induccion-y-sumatorias/Guia_Progresiones-2.pdf", pages: [1,5], steps: [
      t`Para $a_n=(4n+5)/2$, calculamos $a_{n+1}-a_n=[4(n+1)+5-(4n+5)]/2=2$. La diferencia no depende de n: es una progresión aritmética.`,
      t`Si $a_3=5$ y $a_8=15$, escribimos $a_1+2d=5$ y $a_1+7d=15$. Al restar las ecuaciones obtenemos $5d=10$, luego $d=2$ y $a_1=1$.`,
      t`Ahora $a_{20}=a_1+19d=39$. Para sumar, escribimos los términos en ambos órdenes: cada pareja suma $a_1+a_{20}=40$ y hay 20 parejas. Así, $2S_{20}=20\cdot40$ y $S_{20}=400$.`,
      t`Si, en cambio, $a_2=5/2$ y $S_{10}=30$, las ecuaciones son $a_1+d=5/2$ y $5(2a_1+9d)=30$. Sustituir $2a_1=5-2d$ en la segunda da $5+7d=6$.`,
      t`Concluimos $d=1/7$ y $a_1=33/14$. Comprobamos ambos datos: $33/14+1/7=5/2$ y $5(66/14+9/7)=30$.`,
    ] },
  ],
  "progresiones-binomio-2": [
    { title: "Una razón constante y la suma de los rebotes", source: "Induccion-y-sumatorias/Guia_Progresiones-2.pdf", pages: [1,5], steps: [
      t`En $b_n=80/3^n$, el cociente $b_{n+1}/b_n=1/3$ es constante. La diferencia, $-160/3^{n+1}$, no lo es: la progresión es geométrica, no aritmética.`,
      t`Si el séptimo término es 32 veces el segundo y $a_1=3$, entonces $a_1r^6=32a_1r$. No puede ser $r=0$ si el segundo término es no nulo; en ese caso dividimos y obtenemos $r^5=32$, luego $r=2$. Si se permiten términos nulos, $r=0$ también satisface literalmente la igualdad y debe distinguirse.`,
      t`Para la progresión de términos no nulos, $a_{10}=3\cdot2^9=1536$. Restar $S_{12}=3+3r+\cdots+3r^{11}$ de $rS_{12}$ cancela los términos intermedios: $(r-1)S_{12}=3(r^{12}-1)$. Con $r=2$, $S_{12}=12285$.`,
      t`Una pelota cae desde 12 metros y cada rebote alcanza $2/3$ de la altura anterior. Recorre primero 12 metros; después recorre dos veces cada altura de rebote, una al subir y otra al bajar.`,
      t`Las alturas son $8,16/3,32/9,\ldots$. Su suma infinita es $8/(1-2/3)=24$, porque $|2/3|<1$. La distancia total es $12+2\cdot24=60$ metros. El primer descenso no se cuenta dos veces.`,
    ] },
  ],
  "induccion-sumatorias-6": [
    { title: "Resolver primero la suma interior", source: "Induccion-y-sumatorias/Guia_Sumatoria.pdf", pages: [2,5], steps: [
      t`En $\sum_{i=1}^{30}\sum_{k=1}^{20}7ik$, mientras sumamos respecto de k, i permanece fijo. Por eso la suma interior es $7i\sum_{k=1}^{20}k=7i\cdot210=1470i$.`,
      t`Sumamos ahora respecto de i: $1470\sum_{i=1}^{30}i=1470\cdot465=683550$. Cada par de índices del rectángulo se contó una vez.`,
      t`En $\sum_{i=1}^{42}\sum_{k=1}^{i}3i$, el término no depende de k, pero hay i términos en la suma interior. Esta vale $3i\cdot i=3i^2$, no $3i$.`,
      t`Por tanto, la suma doble vale $3\sum_{i=1}^{42}i^2=3\cdot42\cdot43\cdot85/6=76755$. Aquí el límite interior cambia con i: los pares forman un arreglo triangular.`,
      t`Otro ejemplo da $\sum_{i=1}^{6}\sum_{j=1}^{5}(2x_i-3y_j+c)=6000$, $\sum_{i=1}^{6}x_i=18$ y $\sum_{j=1}^{5}y_j=22$. La suma interior es $10x_i-3\cdot22+5c$.`,
      t`Al sumar las seis expresiones: $10\cdot18-6\cdot66+30c=6000$. Así, $30c=6216$ y $c=1036/5$. El factor 30 cuenta las $6\cdot5$ apariciones de la constante.`,
    ] },
  ],
  "geometria-analitica-1": [
    { title: "Obtener la distancia a partir de Pitágoras", source: "Geometria-analitica/Geometria-analitica.pdf", pages: [2,8], steps: [
      t`Dos ejes perpendiculares se cortan en el origen. Las coordenadas de $P=(x,y)$ indican primero la posición horizontal y después la vertical. Las flechas señalan el sentido positivo de cada eje.`,
      t`Para $P=(x_1,y_1)$ y $Q=(x_2,y_2)$, los catetos del triángulo auxiliar tienen longitudes $|x_2-x_1|$ y $|y_2-y_1|$. Pitágoras da $d(P,Q)^2=(x_2-x_1)^2+(y_2-y_1)^2$.`,
      t`Tomamos la raíz no negativa. Intercambiar P y Q no altera los cuadrados, por eso $d(P,Q)=d(Q,P)$. Si ambos están en el eje x, la fórmula se reduce a $|x_2-x_1|$, no a una diferencia con signo.`,
      t`Entre $A=(-3,6)$ y $B=(5,1)$: $d(A,B)=\sqrt{(5+3)^2+(1-6)^2}=\sqrt{64+25}=\sqrt{89}\approx9.43$.`,
      t`Para $A=(-1,-3)$, $B=(6,1)$ y $C=(2,-5)$, obtenemos $AB^2=65$, $BC^2=52$ y $AC^2=13$. Como $65=52+13$, el recíproco de Pitágoras prueba que el ángulo en C es recto.`,
      t`El punto medio promedia las dos coordenadas. Entre $(-2,3)$ y $(4,-2)$ es $((-2+4)/2,(3-2)/2)=(1,1/2)$.`,
    ] },
  ],
  "geometria-analitica-2": [
    { title: "Pendiente, ecuación y rectas especiales", source: "Geometria-analitica/Geometria-analitica.pdf", pages: [9,17], steps: [
      t`Para dos puntos distintos de una recta no vertical, $m=(y_2-y_1)/(x_2-x_1)$. Al multiplicar por la diferencia horizontal se obtiene $y-y_1=m(x-x_1)$, la forma punto-pendiente.`,
      t`Distribuir da $y=mx+(y_1-mx_1)$: la ordenada al origen es $y_1-mx_1$. Si $m>0$ la recta sube; si $m<0$ baja; si $m=0$ es horizontal.`,
      t`En $Ax+By+C=0$, A y B no pueden ser ambos cero. Si $B\ne0$, $y=-(A/B)x-C/B$. Si $B=0$, la recta es vertical: $x=-C/A$. No tiene pendiente definida.`,
      t`Para la paralela a $6x+3y=4$ por $(5,-7)$, despejamos $y=-2x+4/3$, así que la pendiente buscada es −2. Entonces $y+7=-2(x-5)$ y $y=-2x+3$.`,
      t`Dos rectas no verticales son perpendiculares si $m_1m_2=-1$, no +1. Una recta vertical y una horizontal también son perpendiculares, aunque no podamos multiplicar sus pendientes.`,
      t`Como conexión con cálculo: si $f'(x_0)$ existe, la tangente es $y-f(x_0)=f'(x_0)(x-x_0)$. Si $f'(x_0)\ne0$, la normal tiene pendiente $-1/f'(x_0)$; si la derivada es cero, la normal es vertical.`,
    ] },
    { title: "Determinar un parámetro a partir del ángulo", source: "Geometria-analitica/Geometria-analitica.pdf", pages: [18,20], steps: [
      t`Buscamos a para que $3x+y-1=0$ y $2x+ay-8=0$ formen un ángulo de $\pi/4$. Si $a=0$, la segunda recta es vertical y el ángulo no es $\pi/4$, así que consideramos $a\ne0$.`,
      t`Las pendientes son $m_1=-3$ y $m_2=-2/a$. El menor ángulo cumple $\tan\theta=|(m_2-m_1)/(1+m_1m_2)|$ cuando el denominador no es cero.`,
      t`Como $\tan(\pi/4)=1$, obtenemos $|3-2/a|=|1+6/a|$. El caso $a=-6$ daría rectas perpendiculares y queda excluido.`,
      t`Al cuadrar y multiplicar por $a^2$: $9a^2-12a+4=a^2+12a+36$. Por tanto $8a^2-24a-32=0$.`,
      t`Dividimos por 8: $a^2-3a-4=(a-4)(a+1)=0$, de donde $a=4$ o $a=-1$. Ambos valores cumplen la ecuación del ángulo.`,
    ] },
  ],
  "geometria-analitica-3": [
    { title: "Un lugar geométrico definido por una razón de distancias", source: "Geometria-analitica/Geometria-analitica3.pdf", pages: [23,24], steps: [
      t`Buscamos los puntos $P=(x,y)$ tales que $d(P,A)/d(P,L)=4/5$, con $A=(-5,0)$ y $L:5x+16=0$. El denominador exige $x\ne-16/5$.`,
      t`La distancia al punto es $d(P,A)=\sqrt{(x+5)^2+y^2}$. La distancia a la recta es $d(P,L)=|5x+16|/5$.`,
      t`Al cuadrar la razón: $25[(x+5)^2+y^2]/(5x+16)^2=16/25$. Multiplicamos: $625[(x+5)^2+y^2]=16(5x+16)^2$.`,
      t`Distribuir y reunir términos da $225x^2+3690x+625y^2+11529=0$. Dividiendo por 25: $9x^2+(738/5)x+25y^2+11529/25=0$.`,
      t`Completamos el cuadrado en x: $9(x+41/5)^2+25y^2=144$. La ecuación queda $(x+41/5)^2/16+y^2/(144/25)=1$.`,
      t`Es una elipse de centro $(-41/5,0)$ y semiejes 4 y $12/5$. Su intervalo horizontal es $[-61/5,-21/5]$, que no contiene $-16/5$. No se incorporaron puntos donde la razón inicial fuera indefinida.`,
    ] },
  ],
  "geometria-analitica-4": [
    { title: "Centro y radio: tres formas de obtenerlos", source: "Geometria-analitica/Geometria-analitica-2.pdf", pages: [23,27], steps: [
      t`La condición de distancia al centro $C=(h,k)$ es $\sqrt{(x-h)^2+(y-k)^2}=r$. Al cuadrar resulta $(x-h)^2+(y-k)^2=r^2$.`,
      t`Si $C=(-2,3)$ y la circunferencia pasa por $(4,5)$, $r^2=(4+2)^2+(5-3)^2=40$. La ecuación es $(x+2)^2+(y-3)^2=40$.`,
      t`En $3x^2+3y^2-12x+18y=9$, dividimos por 3 y agrupamos: $(x^2-4x)+(y^2+6y)=3$. Sumamos 4 y 9 a ambos lados: $(x-2)^2+(y+3)^2=16$. Centro $(2,-3)$ y radio 4.`,
      t`Si el radio es 5 y el centro es la intersección de $3x-2y-24=0$ y $2x+7y+9=0$, multiplicamos las ecuaciones por 7 y 2. Al sumar: $25x-150=0$, por lo que $x=6$ y luego $y=-3$.`,
      t`La circunferencia buscada es $(x-6)^2+(y+3)^2=25$. El sistema permite hallar el centro; el radio se usa después.`,
      t`En el ejercicio $4x^2+4y^2-16x+12y+16=0$, dividir y completar cuadrados da $(x-2)^2+(y+3/2)^2=9/4$. Centro $(2,-3/2)$ y radio $3/2$.`,
    ] },
  ],
  "geometria-analitica-5": [
    { title: "Deducir la parábola y trasladar su vértice", source: "Geometria-analitica/Geometria-analitica-2.pdf", pages: [28,35], steps: [
      t`Con foco $F=(0,p)$ y directriz $y=-p$, el pie perpendicular desde $P=(x,y)$ es $Q=(x,-p)$. La condición es $d(P,F)=d(P,Q)$.`,
      t`Al cuadrar las distancias: $x^2+(y-p)^2=(y+p)^2$. Desarrollamos: $x^2+y^2-2py+p^2=y^2+2py+p^2$.`,
      t`Cancelamos los términos iguales y obtenemos $x^2=4py$, con $p\ne0$. Si p es positivo abre arriba; si es negativo, abajo. Para $y=-x^2/6$, $4p=-6$, así que $p=-3/2$, foco $(0,-3/2)$ y directriz $y=3/2$.`,
      t`Al trasladar el vértice a $(h,k)$, sustituimos x por $x-h$ e y por $y-k$: $(x-h)^2=4p(y-k)$. Al intercambiar los ejes obtenemos $(y-k)^2=4p(x-h)$.`,
      t`En $2x=y^2+8y+22$, completamos: $2x=(y+4)^2+6$, de modo que $(y+4)^2=2(x-3)$. Leemos $h=3$, $k=-4$ y $p=1/2$.`,
      t`Abre a la derecha; su foco es $(7/2,-4)$ y su directriz $x=5/2$. En el ejercicio de vértice $(-4,2)$ y directriz $y=5$, $2-p=5$ da $p=-3$, luego $(x+4)^2=-12(y-2)$.`,
    ] },
  ],
  "geometria-analitica-6": [
    { title: "Elipse: distancias focales, orientación y excentricidad", source: "Geometria-analitica/Geometria-analitica3.pdf", pages: [2,9], steps: [
      t`Para focos $(-c,0)$ y $(c,0)$, la suma de distancias es $\sqrt{(x+c)^2+y^2}+\sqrt{(x-c)^2+y^2}=2a$, con $a>c$.`,
      t`Aislamos la primera raíz y cuadramos: $4cx=4a^2-4a\sqrt{(x-c)^2+y^2}$. Así $a\sqrt{(x-c)^2+y^2}=a^2-cx$.`,
      t`Al cuadrar otra vez y simplificar queda $(a^2-c^2)x^2+a^2y^2=a^2(a^2-c^2)$. Definiendo $b^2=a^2-c^2>0$, resulta $x^2/a^2+y^2/b^2=1$.`,
      t`Para $2x^2+9y^2=18$, dividimos por 18: $x^2/9+y^2/2=1$. Sus semiejes horizontal y vertical son 3 y $\sqrt2$; sus focos son $(\pm\sqrt7,0)$.`,
      t`En $16x^2+9y^2+64x-18y-71=0$, agrupamos $16(x^2+4x)+9(y^2-2y)=71$. Completar cuadrados exige sumar $16\cdot4+9\cdot1$ al segundo miembro: $16(x+2)^2+9(y-1)^2=144$.`,
      t`Dividir por 144 da $(x+2)^2/9+(y-1)^2/16=1$. El centro es $(-2,1)$ y el eje mayor es vertical. Sus vértices mayores son $(-2,5)$ y $(-2,-3)$; los menores, $(1,1)$ y $(-5,1)$. Los focos son $(-2,1\pm\sqrt7)$.`,
      t`Para evitar confundir letras con direcciones, la excentricidad se calcula como distancia del centro al foco dividida por semieje mayor: aquí $e=\sqrt7/4$. Si e se acerca a 0 la elipse se aproxima a una circunferencia; si se acerca a 1, se alarga.`,
    ] },
  ],
  "geometria-analitica-7": [
    { title: "Hipérbola: del rectángulo auxiliar a las asíntotas", source: "Geometria-analitica/Geometria-analitica3.pdf", pages: [12,17], steps: [
      t`La condición focal es $|d(P,F_1)-d(P,F_2)|=2a$. A diferencia de la elipse, aquí se resta. En la forma horizontal $x^2/a^2-y^2/b^2=1$, $c^2=a^2+b^2$.`,
      t`Para $9x^2-4y^2=36$, dividimos por 36: $x^2/4-y^2/9=1$. Los vértices son $(\pm2,0)$ y los focos $(\pm\sqrt{13},0)$.`,
      t`Dibujamos el rectángulo auxiliar con semiancho 2 y semialto 3. Sus diagonales dan las asíntotas $y=\pm3x/2$. La curva abre en la dirección de su término positivo.`,
      t`En $9x^2-4y^2-54x-16y+29=0$, agrupamos $9(x^2-6x)-4(y^2+4y)=-29$. Al completar cuadrados se suma 81 pero se resta 16: $9(x-3)^2-4(y+2)^2=36$.`,
      t`Así $(x-3)^2/4-(y+2)^2/9=1$. Centro $(3,-2)$, vértices $(1,-2)$ y $(5,-2)$ y focos $(3\pm\sqrt{13},-2)$.`,
      t`Las asíntotas pasan por el centro, no por el origen: $y+2=\pm(3/2)(x-3)$. Sus pendientes no cambian con la traslación.`,
    ] },
  ],
  "geometria-analitica-8": [
    { title: "Clasificar una cónica y comprobar una parametrización", source: "Geometria-analitica/Geometria-analitica3.pdf", pages: [10,20], steps: [
      t`Una circunferencia completa no es una gráfica $y=f(x)$: para algunas abscisas tiene dos ordenadas. Podemos describir ambos valores usando un parámetro: $x=\cos t$, $y=\sin t$, con $0\le t<2\pi$.`,
      t`Para una elipse, $x=a\cos t$, $y=b\sin t$. Sustituir da $b^2x^2+a^2y^2=a^2b^2(\cos^2t+\sin^2t)=a^2b^2$. Al dividir obtenemos su ecuación.`,
      t`Una parábola $x^2=4py$ se parametriza con $x=t$, $y=t^2/(4p)$ para todo t real. El parámetro recorre puntos de la curva, mientras p fija su forma.`,
      t`Sin término xy, los signos de los coeficientes de $x^2$ e $y^2$ orientan la clasificación, pero hay que completar cuadrados y revisar el segundo miembro para descartar degeneraciones.`,
      t`Por ejemplo, $x^2+4y^2-10x+40y+109=0$ da $(x-5)^2+4(y+5)^2=16$, luego $(x-5)^2/16+(y+5)^2/4=1$. Es una elipse horizontal de centro $(5,-5)$.`,
      t`Sus vértices mayores son $(1,-5)$ y $(9,-5)$, los menores $(5,-7)$ y $(5,-3)$; sus focos son $(5\pm\sqrt{12},-5)$. Una parametrización es $x=5+4\cos t$, $y=-5+2\sin t$.`,
    ] },
  ],
  "polinomios-1": [
    { title: "Coeficientes, dominio y producto distribuido", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [2,6], steps: [
      t`En $p(x)=\sum_{i=0}^n a_ix^i$, $a_0$ es el término independiente y $a_n\ne0$ el coeficiente principal. Los exponentes son enteros no negativos. Los polinomios reales forman $\mathbb R[x]$.`,
      t`La constante 5 tiene grado 0; $x-7$ tiene grado 1; $x^2+x+1$ tiene grado 2. La expresión $1/x$ no es un polinomio en x.`,
      t`Aunque $(x^2+5x+6)/(x+2)$ se simplifica a $x+3$ para $x\ne-2$, la expresión original no está definida en −2. Como funciones con sus dominios naturales, no es la misma función polinómica definida en todo $\mathbb R$.`,
      t`Para sumar, alinea las potencias y asigna coeficiente cero a las ausentes: $(x^2+1)+(x-1)=x^2+x$. Los términos principales pueden cancelarse, como en $(x^2+1)+(-x^2+x)=x+1$.`,
      t`Para multiplicar $(x^2+x+1)(3x^2+1)$ distribuimos: $3x^4+x^2+3x^3+x+3x^2+1$. Reuniendo potencias queda $3x^4+3x^3+4x^2+x+1$. El grado es $2+2=4$.`,
    ] },
  ],
  "polinomios-2": [
    { title: "División larga: cada producto y cada resta", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [7,9], steps: [
      t`Dividimos $p(x)=x^4-x^3+4x^2-12x+3$ por $g(x)=x^2+2x-1$, ordenados de mayor a menor grado. En cada paso elegimos un término que cancele la mayor potencia restante.`,
      t`Primero $x^4/x^2=x^2$. Multiplicamos $x^2g(x)=x^4+2x^3-x^2$. Al restarlo de p queda $-3x^3+5x^2-12x+3$.`,
      t`Después $-3x^3/x^2=-3x$. Multiplicamos $-3xg(x)=-3x^3-6x^2+3x$. Restamos toda esta expresión, cambiando todos sus signos: queda $11x^2-15x+3$.`,
      t`Finalmente $11x^2/x^2=11$. Restamos $11g(x)=11x^2+22x-11$ y obtenemos $-37x+14$.`,
      t`El resto tiene grado 1, menor que el grado 2 del divisor, así que terminamos. $q(x)=x^2-3x+11$ y $r(x)=-37x+14$. La comprobación es $p(x)=g(x)q(x)+r(x)$.`,
    ] },
    { title: "Dos divisiones sintéticas con potencias ausentes", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [10,11], steps: [
      t`Para dividir $2x^4+3x^3-x-5$ por $x+2$, usamos −2 y los coeficientes $2,3,0,-1,-5$. El cero conserva el lugar de $x^2$.`,
      t`Bajamos 2. Luego $3+(-2)2=-1$, $0+(-2)(-1)=2$, $-1+(-2)2=-5$ y $-5+(-2)(-5)=5$.`,
      t`La fila final es $2,-1,2,-5,5$. El cociente es $2x^3-x^2+2x-5$ y el resto es 5: $2x^4+3x^3-x-5=(x+2)(2x^3-x^2+2x-5)+5$.`,
      t`Para $2x^4-5x^2+3x-14$ dividido por $x-2$, usamos 2 y $2,0,-5,3,-14$. Las sumas sucesivas dan $2,4,3,9,4$.`,
      t`El resultado es $q(x)=2x^3+4x^2+3x+9$ y $r=4$. En ambos casos el cociente tiene un grado menos que el dividendo; el resto es constante o cero.`,
    ] },
  ],
  "polinomios-3": [
    { title: "Evaluación, resto y factor en los ejemplos", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [12,15], steps: [
      t`Si $p(x)=q(x)(x-a)+r$, evaluamos en a: $p(a)=q(a)(a-a)+r=0+r=r$. El factor que se anula es $a-a$, aunque $q(a)$ no sea cero.`,
      t`En $p(x)=3x^5+5x^4-4x^3+7x+3$, los coeficientes para dividir por $x+2$ son $3,5,-4,0,7,3$. Usamos −2 y obtenemos $3,-1,-2,4,-1,5$.`,
      t`Así $q(x)=3x^4-x^3-2x^2+4x-1$, $r=5$ y $p(-2)=5$, sin desarrollar las cinco potencias de la evaluación directa.`,
      t`El resto es cero si y solo si $x-a$ es factor de p. En ese caso a es una raíz: $p(a)=0$. Por ejemplo, $x^2-x-6=(x-3)(x+2)$ tiene raíces 3 y −2.`,
      t`Para $32x^{20}+33x^5+1$, evaluar en −1 da $32(-1)^{20}+33(-1)^5+1=32-33+1=0$. Por ello $x+1$ divide al polinomio; no es necesario calcular antes el cociente.`,
    ] },
  ],
  "polinomios-4": [
    { title: "Raíces racionales de un polinomio de cuarto grado", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [20,24], steps: [
      t`Para $p(x)=4x^4-4x^3-5x^2+x+1$, las candidatas racionales reducidas son $\pm1,\pm1/2,\pm1/4$. Los numeradores dividen 1 y los denominadores dividen 4.`,
      t`Evaluamos: $p(1)=p(-1)=-3$, mientras que $p(1/2)=1/4-1/2-5/4+1/2+1=0$.`,
      t`La división sintética por $x-1/2$ da $4,-2,-6,-2,0$: $p(x)=2(x-1/2)(2x^3-x^2-3x-1)$. Se conserva el factor 2.`,
      t`En el cúbico restante, −1/2 es raíz. La nueva fila es $2,-2,-2,0$, así que $p(x)=4(x-1/2)(x+1/2)(x^2-x-1)$.`,
      t`La cuadrática da $x=(1\pm\sqrt5)/2$. Las cuatro raíces son $1/2,-1/2,(1+\sqrt5)/2,(1-\sqrt5)/2$. Las dos últimas son irracionales: no tenían que figurar en la lista de candidatas racionales.`,
      t`La regla de Descartes solo cuenta posibilidades. Por ejemplo, $3x^6+4x^5+3x^3-x-3$ tiene un cambio de signo y exactamente una raíz positiva; su evaluación en −x tiene tres cambios, por lo que puede tener tres o una raíces negativas, contando multiplicidades.`,
    ] },
  ],
  "polinomios-5": [
    { title: "Una factorización cambia según el conjunto de coeficientes", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [16,19], steps: [
      t`En $p(x)=x^4+x^3-x-1$, $p(1)=0$. La división por $x-1$ con coeficientes $1,1,0,-1,-1$ produce $x^3+2x^2+2x+1$.`,
      t`El cociente se anula en −1. Al dividirlo por $x+1$ obtenemos $x^2+x+1$. Por tanto $p(x)=(x-1)(x+1)(x^2+x+1)$.`,
      t`La cuadrática tiene discriminante $1-4=-3$, así que no se descompone en factores lineales reales. Esa es la factorización en $\mathbb R[x]$.`,
      t`En $\mathbb C$, sus raíces son $z_\pm=(-1\pm i\sqrt3)/2$. Así $p(x)=(x-1)(x+1)(x-z_+)(x-z_-)$. Hay cuatro raíces contando multiplicidad, como indica el grado.`,
      t`La multiplicidad debe ser exacta: a tiene multiplicidad m cuando $(x-a)^m$ divide a p y la potencia siguiente no. En $x(x-1)^2$, 0 es simple y 1 es doble.`,
    ] },
    { title: "Usar una raíz compleja y su conjugada", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [25,28], steps: [
      t`Si p tiene coeficientes reales y $p(z)=0$, entonces $p(\overline z)=\overline{p(z)}=0$. Las raíces no reales aparecen con sus conjugadas.`,
      t`Para $p(x)=2x^3-13x^2+26x-10$, conocer la raíz $3-i$ da también $3+i$. El producto de sus factores es $(x-3+i)(x-3-i)=(x-3)^2+1=x^2-6x+10$.`,
      t`Dividimos p por esa cuadrática: el primer término es 2x. Restar $2x(x^2-6x+10)$ deja $-x^2+6x-10$.`,
      t`El siguiente término es −1 y al restar $-(x^2-6x+10)$ queda cero. Así el cociente es $2x-1$.`,
      t`En los reales: $p(x)=(x^2-6x+10)(2x-1)$. En los complejos: $p(x)=(x-(3-i))(x-(3+i))(2x-1)$. La tercera raíz es $1/2$.`,
    ] },
  ],
  "polinomios-6": [
    { title: "Primero dividir; después descomponer", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [29,36], steps: [
      t`Si el numerador tiene grado mayor o igual que el denominador, el algoritmo de división da $N/D=q+r/D$. Solo se descompone la fracción propia $r/D$.`,
      t`Por ejemplo, $(x^4-10x^2+3x+1)/(x^2-4)=x^2-6+(3x-23)/(x^2-4)$, con $x\ne\pm2$. La primera resta deja $-6x^2+3x+1$ y la segunda, $3x-23$.`,
      t`En $(10x^2-8x-9)/(2x^3+x^2-13x+6)$ ya tenemos una fracción propia. La raíz −3 del denominador deja el cociente $2x^2-5x+2=(x-2)(2x-1)$.`,
      t`Planteamos $A/(x+3)+B/(x-2)+C/(2x-1)$. La identidad de numeradores es $10x^2-8x-9=A(x-2)(2x-1)+B(x+3)(2x-1)+C(x+3)(x-2)$.`,
      t`En $x=-3$, $105=35A$ y $A=3$. En $x=2$, $15=15B$ y $B=1$. En $x=1/2$, $-21/2=(-21/4)C$ y $C=2$.`,
      t`El resultado es $3/(x+3)+1/(x-2)+2/(2x-1)$, con $x\ne-3,2,1/2$. No se pierde el factor 2 del término lineal $2x-1$.`,
    ] },
    { title: "Factor lineal repetido: comparar todos los coeficientes", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [37,39], steps: [
      t`Como $x^3+3x^2+3x+1=(x+1)^3$, planteamos $(2x^2+3x+3)/(x+1)^3=A/(x+1)+B/(x+1)^2+C/(x+1)^3$.`,
      t`Al multiplicar por $(x+1)^3$ obtenemos $2x^2+3x+3=A(x+1)^2+B(x+1)+C$.`,
      t`Distribuimos: $Ax^2+(2A+B)x+(A+B+C)$. Comparar coeficientes da $A=2$, $2A+B=3$, $A+B+C=3$.`,
      t`Por tanto $A=2$, $B=-1$ y $C=2$. También se obtiene C evaluando la identidad en −1: $2-3+3=C=2$.`,
      t`La descomposición es $2/(x+1)-1/(x+1)^2+2/(x+1)^3$, con $x\ne-1$. Se necesitan todas las potencias hasta la tercera.`,
    ] },
  ],
  "polinomios-7": [
    { title: "Cuadrática irreducible y cuadrática repetida", source: "Complejos-y-polinomios/Polinomios.pdf", pages: [40,43], steps: [
      t`Para $(6x-5)/[(x-2)(x^2+x+1)]$, el discriminante de $x^2+x+1$ es −3. Planteamos $A/(x-2)+(Bx+C)/(x^2+x+1)$.`,
      t`Al eliminar denominadores, $6x-5=A(x^2+x+1)+(Bx+C)(x-2)$. En $x=2$, $7=7A$, así que $A=1$.`,
      t`Después $6x-5=(B+1)x^2+(1-2B+C)x+(1-2C)$. Resulta $B=-1$, $C=3$, y el término independiente confirma $1-6=-5$.`,
      t`La respuesta es $1/(x-2)+(-x+3)/(x^2+x+1)$, con $x\ne2$.`,
      t`Para $(x^2-x+9)/(x^2+9)^2$, la forma general es $(Ax+B)/(x^2+9)+(Cx+D)/(x^2+9)^2$.`,
      t`Igualar numeradores da $x^2-x+9=Ax^3+Bx^2+(9A+C)x+(9B+D)$. Incluso el coeficiente ausente de $x^3$ cuenta: $A=0$, $B=1$, $9A+C=-1$, $9B+D=9$.`,
      t`Por tanto $C=-1$, $D=0$ y queda $1/(x^2+9)-x/(x^2+9)^2$. Está definida para todo x real porque $x^2+9>0$.`,
    ] },
  ],
  "conjuntos-1": [
    { title: "Una misma colección, dos formas de describirla", source: "Conjuntos/conjuntos-1.pdf", pages: [2,3], steps: [
      t`Por extensión, las vocales se escriben $V=\{a,e,i,o,u\}$. Por comprensión, $V=\{x\in U:x\text{ es una vocal}\}$, tomando como universo las letras del alfabeto. Las llaves encierran elementos; la condición decide cuáles entran.`,
      t`Cambiar el orden de las vocales no cambia V. Esto no sucede con un par ordenado: $(a,b)$ y $(b,a)$ pueden ser distintos.`,
      t`Para $S=\{x\in\mathbb R:\cos x=0\}$, la condición se cumple en $\pi/2$, $3\pi/2$ y en los ángulos obtenidos al seguir avanzando o retrocediendo múltiplos de $\pi$. Así, $S=\{\pi/2+k\pi:k\in\mathbb Z\}$.`,
      t`En $A\subseteq B$, lo que afirmamos es $x\in A\Rightarrow x\in B$ para todo x. En cambio, $x\in A$ relaciona un objeto con el conjunto que lo contiene.`,
    ] },
  ],
  "conjuntos-2": [
    { title: "Leer las regiones de un diagrama de Venn", source: "Conjuntos/conjuntos-1.pdf", pages: [4,7], steps: [
      t`Representa el universo con un rectángulo y A y B con dos regiones. Si coloreas A de un color y B de otro, $A\cup B$ reúne lo coloreado al menos una vez y $A\cap B$ lo coloreado dos veces.`,
      t`El complemento $A^c$ es lo que queda en el rectángulo fuera de A. Por eso $\varnothing^c=U$, $U^c=\varnothing$ y $(A^c)^c=A$.`,
      t`Para $A\setminus B$, conserva solamente la parte de A que no pertenece a B. Intercambiar los conjuntos cambia la región, de modo que la diferencia no es conmutativa.`,
      t`Para $A\triangle B$, conserva lo que está en exactamente uno: $(A\cup B)\setminus(A\cap B)=(A\setminus B)\cup(B\setminus A)$. Esta operación sí es conmutativa.`,
      t`Si $A\cap B=\varnothing$, los conjuntos son disjuntos. Si A está completamente dentro de B, se cumple $A\subseteq B$. Son dos situaciones distintas.`,
    ] },
  ],
  "conjuntos-3": [
    { title: "Demostración algebraica, igualdad por igualdad", source: "Conjuntos/conjuntos-1.pdf", pages: [7,10], steps: [
      t`Queremos demostrar $(A\cap B)\setminus(A\cap C)=A\cap(B\setminus C)$. Empezamos por escribir la diferencia usando complemento: $(A\cap B)\cap(A\cap C)^c$.`,
      t`De Morgan transforma el complemento: $(A\cap B)\cap(A^c\cup C^c)$.`,
      t`Distribuimos la intersección: $[(A\cap B)\cap A^c]\cup[(A\cap B)\cap C^c]$.`,
      t`Reagrupamos: $[(A\cap A^c)\cap B]\cup[A\cap(B\cap C^c)]$. Como $A\cap A^c=\varnothing$, el primer conjunto es vacío.`,
      t`La unión con el vacío no agrega elementos, así que queda $A\cap(B\cap C^c)=A\cap(B\setminus C)$. Cada igualdad está justificada por una ley.`,
      t`Otras inclusiones útiles son $A\cap B\subseteq A\subseteq A\cup B$, la transitividad ($A\subseteq B$ y $B\subseteq C$ implican $A\subseteq C$) y $A\subseteq B\Leftrightarrow B^c\subseteq A^c$. Al complementar se invierte la inclusión.`,
    ] },
  ],
  "conjuntos-4": [
    { title: "Cardinalidad y encuesta de dos revistas", source: "Conjuntos/conjuntos-1.pdf", pages: [10,12], steps: [
      t`Para un conjunto finito A, $|A|$ cuenta sus elementos: podemos emparejarlos uno a uno con $\{1,\ldots,n\}$. Una biyección con un subconjunto cualquiera de los naturales no garantiza finitud: $n\mapsto2n$ empareja los naturales con los pares y ambos conjuntos son infinitos.`,
      t`Si A y B son finitos, $|A\cup B|=|A|+|B|-|A\cap B|$. Si son disjuntos, el último término es cero. Además, $|A\setminus B|=|A\cup B|-|B|$ y $|A^c|=|U|-|A|$ para U finito.`,
      t`En una encuesta a 50 personas sobre dos revistas, sean a quienes leen solo A, b quienes leen ambas, c quienes leen solo B y d quienes no leen ninguna. Estas cuatro regiones no se superponen y satisfacen $a+b+c+d=50$.`,
      t`Las condiciones son $b=2a$, $b=3c$ y $b=4d$. Despejamos $a=b/2$, $c=b/3$, $d=b/4$ y sustituimos: $b/2+b+b/3+b/4=50$.`,
      t`Multiplicamos por 12: $6b+12b+4b+3b=600$, por lo que $25b=600$ y $b=24$. Así $a=12$, $c=8$, $d=6$.`,
      t`Quienes leen A son los de solo A y los de ambas revistas: $|A|=a+b=12+24=36$. Comprobación: $12+24+8+6=50$.`,
    ] },
  ],
  "progresiones-binomio-3": [
    { title: "Coeficientes binomiales: valores y demostraciones", source: "Induccion-y-sumatorias/factorial-y-teorema-del-bonomio.pdf", pages: [2,5], steps: [
      t`La definición recursiva $0!=1$, $n!=n(n-1)!$ da $3!=3\cdot2\cdot1=6$. Para $0\le k\le n$, $\binom nk=n!/[(n-k)!k!]$; si $k>n$, se define como cero.`,
      t`Por ejemplo, $\binom53=5!/(2!3!)=(5\cdot4)/(2\cdot1)=10$ y $\binom23=0$. En los extremos: $\binom n0=\binom nn=1$ y $\binom n1=\binom n{n-1}=n$.`,
      t`La simetría se prueba sustituyendo: $\binom n{n-k}=n!/[(n-(n-k))!(n-k)!]=n!/[k!(n-k)!]=\binom nk$.`,
      t`Para $0\le k<n$, llevamos $\binom nk+\binom n{k+1}$ al denominador común $(n-k)!(k+1)!$: el numerador es $n!(k+1)+n!(n-k)=n!(n+1)=(n+1)!$.`,
      t`El resultado es $(n+1)!/[(n-k)!(k+1)!]=\binom{n+1}{k+1}$, la regla de Pascal. El caso de borde $k=n$ se verifica aparte: $1+0=1$.`,
      t`Para $1\le k\le n$, también $k\binom nk=kn!/[k!(n-k)!]=n!/[(k-1)!(n-k)!]=n\binom{n-1}{k-1}$. Se usa $k!=k(k-1)!$.`,
    ] },
  ],
  "progresiones-binomio-4": [
    { title: "Del triángulo de Pascal al término general", source: "Induccion-y-sumatorias/factorial-y-teorema-del-bonomio.pdf", pages: [6,9], steps: [
      t`Las primeras filas de coeficientes son 1; 1,1; 1,2,1; 1,3,3,1; 1,4,6,4,1; 1,5,10,10,5,1. Cada entrada interior suma las dos que tiene encima; los bordes son 1.`,
      t`En $(a+b)^n$ hay n+1 términos: comienza con $a^n$, termina con $b^n$ y los exponentes de a y b siempre suman n. El exponente de a desciende mientras el de b asciende.`,
      t`Por ejemplo, $(a+b)^4=a^4+4a^3b+6a^2b^2+4ab^3+b^4$. La fila n del triángulo contiene $\binom n0,\ldots,\binom nn$.`,
      t`Al reemplazar b por −b aparece $(-1)^k$ en el término general. Por eso los signos de $(a-b)^n$ se alternan.`,
      t`Con $a=b=1$, el binomio da $2^n=\sum_{k=0}^n\binom nk$. Para $n\ge1$, tomar $a=1$, $b=-1$ da $0=\sum_{k=0}^n(-1)^k\binom nk$.`,
    ] },
    { title: "Quinto término, término en x³ y término independiente", source: "Induccion-y-sumatorias/factorial-y-teorema-del-bonomio.pdf", pages: [10,13], steps: [
      t`En $(\frac32x^2-\frac1{3x})^9$, con $x\ne0$, el término de posición k+1 es $T_{k+1}=\binom9k(\frac32x^2)^{9-k}(-\frac1{3x})^k$, donde $k=0,\ldots,9$.`,
      t`Separamos constantes y potencias: $T_{k+1}=\binom9k(-1)^k2^{-(9-k)}3^{9-2k}x^{18-3k}$. El exponente de x es $2(9-k)-k$, no $2(9-k)$ solamente.`,
      t`El quinto término corresponde a $k=4$, no a 5: $T_5=\binom94\,3x^6/2^5=126\cdot3x^6/32=189x^6/16$.`,
      t`Para encontrar $x^5$, resolvemos $18-3k=5$, que da $k=13/3$. No es un índice entero admisible, así que ese término no aparece.`,
      t`Para $x^3$, $18-3k=3$ da $k=5$. Así $T_6=\binom95(-1)2^{-4}3^{-1}x^3=-126x^3/48=-21x^3/8$.`,
      t`Para el término independiente, $18-3k=0$ da $k=6$: $T_7=\binom96\,2^{-3}3^{-3}=84/(8\cdot27)=7/18$.`,
    ] },
  ],
  "induccion-sumatorias-1": [
    { title: "Primer ejemplo: por qué 3ⁿ−1 es par", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [2,4], steps: [
      t`La proposición $P(n)$ es «$3^n-1$ es par». Queremos demostrarla para todo $n\ge1$, no solo para algunos valores.`,
      t`Caso base: para $n=1$, $3^1-1=2$, que es par. Así se verifica $P(1)$.`,
      t`Hipótesis inductiva: fija un entero arbitrario $k\ge1$ y supone que $P(k)$ es verdadera. Ser par significa que existe un entero $m$ tal que $3^k-1=2m$.`,
      t`Objetivo del paso: demostrar $P(k+1)$, es decir, escribir $3^{k+1}-1$ como dos veces un entero. No suponemos este resultado.`,
      t`Separar $3=2+1$ permite hacer aparecer exactamente la expresión de la hipótesis: $3^{k+1}-1=3\cdot3^k-1=(2+1)3^k-1=2\cdot3^k+(3^k-1)$.`,
      t`Ahora sustituimos $3^k-1=2m$: $3^{k+1}-1=2\cdot3^k+2m=2(3^k+m)$. Como $3^k+m$ es entero, el resultado es par.`,
      t`La base y el paso inductivo permiten concluir que $3^n-1$ es par para todo entero $n\ge1$. Si se incluye $n=0$, ese caso también se verifica directamente: $3^0-1=0$.`,
    ] },
    { title: "Divisibilidad por 3: localizar la hipótesis", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [5,6], steps: [
      t`Queremos demostrar que $11^n-8^n$ es divisible por 3 para todo $n\ge1$. Base: $11^1-8^1=3$.`,
      t`Hipótesis: $11^k-8^k=3m$ para algún entero $m$. El objetivo es obtener un múltiplo de 3 para el exponente $k+1$.`,
      t`Desarrollamos las potencias: $11^{k+1}-8^{k+1}=11\cdot11^k-8\cdot8^k=(8+3)11^k-8\cdot8^k$.`,
      t`Distribuimos y agrupamos: $8\cdot11^k+3\cdot11^k-8\cdot8^k=8(11^k-8^k)+3\cdot11^k$.`,
      t`Aplicamos la hipótesis solo a la diferencia entre paréntesis: $8(3m)+3\cdot11^k=3(8m+11^k)$. El paréntesis es entero.`,
      t`Esto verifica $P(k+1)$. Por inducción, la divisibilidad vale para todos los naturales positivos.`,
    ] },
    { title: "Suma de los primeros naturales: demostración completa", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [6,7], steps: [
      t`La afirmación es $1+2+\cdots+n=n(n+1)/2$. Caso base: $1=1(1+1)/2$.`,
      t`Hipótesis: $1+2+\cdots+k=k(k+1)/2$. Lo que debemos probar es $1+2+\cdots+k+(k+1)=(k+1)(k+2)/2$.`,
      t`Separamos el último sumando: $(1+2+\cdots+k)+(k+1)$. La hipótesis reemplaza únicamente el primer paréntesis.`,
      t`Obtenemos $k(k+1)/2+(k+1)=[k(k+1)+2(k+1)]/2$.`,
      t`Sacamos el factor común $k+1$: $[k(k+1)+2(k+1)]/2=(k+1)(k+2)/2$. Esta es exactamente la fórmula para el índice siguiente.`,
      t`Concluimos por inducción. Además, $n(n+1)/2$ es entero porque entre dos naturales consecutivos uno es par.`,
    ] },
    { title: "Inducción con desigualdades: justificar el paso intermedio", source: "Induccion-y-sumatorias/Ejercicios-resueltos-PRINCIPIO-DE-INDUCCION-MATEMATICA.pdf", pages: [8,8], steps: [
      t`Queremos demostrar $3^n>n^2$ para todo $n\ge1$. Comprobamos $3>1$ y $9>4$. Para iniciar una cadena desde n=3, comprobamos también $27>9$.`,
      t`Hipótesis: fija $k\ge3$ y supone $3^k>k^2$. Multiplicar por el número positivo 3 conserva el orden: $3^{k+1}>3k^2$.`,
      t`Todavía no llegamos al objetivo $(k+1)^2$. Falta comparar $3k^2$ con esa expresión. Como $k\ge3$, $k^2>2k$ y $k^2>1$.`,
      t`Sumamos estas desigualdades: $2k^2>2k+1$. Agregar $k^2$ a ambos lados da $3k^2>k^2+2k+1=(k+1)^2$.`,
      t`Encadenamos $3^{k+1}>3k^2>(k+1)^2$. Esto prueba el paso inductivo para k≥3; junto con los primeros casos, prueba la afirmación para todo n≥1. No se reemplaza $3^{k+1}$ por $3k^2$: se usa una desigualdad entre ellos.`,
    ] },
  ],
  "induccion-sumatorias-2": [
    { title: "De una cadena de igualdades a una fórmula explícita", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [9,12], steps: [
      t`Considera ahora $4=3/a_1=a_1+3/a_2=a_2+3/a_3=\cdots=a_k+3/a_{k+1}$. De $4=3/a_1$ sale $a_1=3/4$.`,
      t`De $4=a_k+3/a_{k+1}$ despejamos $3/a_{k+1}=4-a_k$ y por tanto $a_{k+1}=3/(4-a_k)$.`,
      t`Así, $a_2=3/(4-3/4)=3/(13/4)=12/13$. Después $a_3=3/(4-12/13)=3/(40/13)=39/40$.`,
      t`Proponemos $a_n=(3^{n+1}-3)/(3^{n+1}-1)$. Base: para $n=1$ da $(9-3)/(9-1)=6/8=3/4$.`,
      t`Hipótesis: $a_k=(3^{k+1}-3)/(3^{k+1}-1)$. Objetivo: $a_{k+1}=(3^{k+2}-3)/(3^{k+2}-1)$.`,
      t`Sustituimos en la recurrencia: $a_{k+1}=3/[4-(3^{k+1}-3)/(3^{k+1}-1)]$.`,
      t`Llevamos el denominador a una sola fracción: $4-a_k=[4(3^{k+1}-1)-(3^{k+1}-3)]/(3^{k+1}-1)$.`,
      t`Simplificamos su numerador: $4\cdot3^{k+1}-4-3^{k+1}+3=3\cdot3^{k+1}-1=3^{k+2}-1$.`,
      t`Dividir por una fracción es multiplicar por su inversa: $a_{k+1}=3(3^{k+1}-1)/(3^{k+2}-1)=(3^{k+2}-3)/(3^{k+2}-1)$. Queda probado el paso inductivo.`,
      t`Los denominadores son positivos para $n\ge1$. Además, $0<a_n<1$, por lo que $4-a_n>3$ y la recurrencia no divide por cero.`,
    ] },
  ],
  "induccion-sumatorias-3": [
    { title: "Leer, distribuir y separar una sumatoria", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [13,16], steps: [
      t`Sean $(a_i)_{i\in\mathbb N}$ y $(b_i)_{i\in\mathbb N}$ sucesiones reales, y $c\in\mathbb R$ una constante. Las propiedades siguientes se entienden desarrollando las sumas: así vemos qué operaciones permiten reunir o separar términos.`,
      t`Para una constante c, $\sum_{i=1}^n ca_i=ca_1+\cdots+ca_n=c(a_1+\cdots+a_n)=c\sum_{i=1}^n a_i$.`,
      t`Asimismo, $\sum_{i=1}^n(a_i\pm b_i)=(a_1\pm b_1)+\cdots+(a_n\pm b_n)=\sum_{i=1}^n a_i\pm\sum_{i=1}^n b_i$.`,
      t`Una constante se suma tantas veces como índices haya: $\sum_{i=1}^n c=c+c+\cdots+c=nc$, y en general $\sum_{i=p}^q c=(q-p+1)c$. Por ejemplo, $\sum_{i=3}^7 4=5\cdot4=20$: hay cinco términos, no siete.`,
      t`Si $1\le m\le n$, separar la lista de términos da $\sum_{i=1}^n a_i=\sum_{i=1}^m a_i+\sum_{i=m+1}^n a_i$. Por tanto, $\sum_{i=m+1}^n a_i=\sum_{i=1}^n a_i-\sum_{i=1}^m a_i$. El término de índice m no se cuenta dos veces.`,
      t`También podemos cambiar el índice sin cambiar los términos sumados. Con $j=i+r$, obtenemos $\sum_{i=p}^q a_i=\sum_{j=p+r}^{q+r}a_{j-r}$. Con $j=i-r$, obtenemos $\sum_{i=p}^q a_i=\sum_{j=p-r}^{q-r}a_{j+r}$. Cambiamos simultáneamente los límites y el argumento; en ambos casos el primer término sigue siendo $a_p$ y el último, $a_q$.`,
      t`Estas reglas permiten separar sumas y restas o sacar factores constantes. No permiten, en general, escribir la suma de productos como el producto de las sumas. Cambiar solamente la letra del índice tampoco cambia la suma: es una variable local de esa expresión.`,
    ] },
  ],
  "induccion-sumatorias-4": [
    { title: "Cambio de índice en la suma desde 7 hasta 25", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [16,17], steps: [
      t`La regla general es $\sum_{i=p}^q a_i=\sum_{j=p-r}^{q-r}a_{j+r}$. Como $j=i-r$, debemos cambiar a la vez los límites y el término sumado.`,
      t`En $S=\sum_{i=7}^{25}(3i-2)$, la linealidad da $S=3\sum_{i=7}^{25}i-\sum_{i=7}^{25}2$.`,
      t`Con $j=i-6$, los límites pasan a 1 y 19: $\sum_{i=7}^{25}i=\sum_{j=1}^{19}(j+6)=19\cdot20/2+6\cdot19=304$.`,
      t`La constante 2 aparece 19 veces, de modo que $S=3\cdot304-2\cdot19=874$.`,
      t`También podemos restar las sumas iniciales: $\sum_{i=7}^{25}i=25\cdot26/2-6\cdot7/2=325-21=304$. Ambas rutas conservan los mismos términos.`,
      t`La fórmula de cuartas potencias puede escribirse $\sum_{i=1}^n i^4=n(n+1)(6n^3+9n^2+n-1)/30$. Es equivalente a la forma factorizada porque $(2n+1)(3n^2+3n-1)=6n^3+9n^2+n-1$.`,
    ] },
  ],
  "induccion-sumatorias-5": [
    { title: "La fórmula telescópica también se demuestra por inducción", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [18,20], steps: [
      t`Queremos probar $\sum_{i=1}^N(a_{i+1}-a_i)=a_{N+1}-a_1$. Para $N=1$, ambos lados son $a_2-a_1$.`,
      t`Hipótesis: $\sum_{i=1}^k(a_{i+1}-a_i)=a_{k+1}-a_1$. Para pasar al siguiente índice añadimos el término $a_{k+2}-a_{k+1}$.`,
      t`Entonces $\sum_{i=1}^{k+1}(a_{i+1}-a_i)=(a_{k+1}-a_1)+(a_{k+2}-a_{k+1})=a_{k+2}-a_1$. Se cancela $a_{k+1}$, no los extremos.`,
      t`Para $a_i=1/i$, resulta $\sum_{i=1}^{100}(1/(i+1)-1/i)=1/101-1=-100/101$. El orden de la resta determina el signo.`,
      t`Para $a_k=k^3$, $\sum_{k=1}^N[k^3-(k+1)^3]=1-(N+1)^3=-N^3-3N^2-3N$. Aquí la resta tiene el orden contrario.`,
      t`Otra ruta es expandir: $k^3-(k+1)^3=-3k^2-3k-1$. Sumando y usando las fórmulas de $\sum k^2$, $\sum k$ y $\sum1$, se obtiene el mismo resultado.`,
    ] },
    { title: "Fracciones parciales: dos maneras de hallar los coeficientes", source: "Induccion-y-sumatorias/Induccion-y-sumatorias.pdf", pages: [21,26], steps: [
      t`Factorizamos $k^2+5k+6=(k+2)(k+3)$ y planteamos $1/[(k+2)(k+3)]=A/(k+2)+B/(k+3)$.`,
      t`Al reunir fracciones e igualar numeradores: $1=A(k+3)+B(k+2)=(A+B)k+3A+2B$.`,
      t`Comparar coeficientes da $A+B=0$ y $3A+2B=1$. De $B=-A$ resulta $A=1$ y $B=-1$.`,
      t`Alternativamente, en la identidad de polinomios $1=A(k+3)+B(k+2)$ evaluamos $k=-3$ y $k=-2$: obtenemos $B=-1$ y $A=1$. Esto se hace después de eliminar denominadores; la fracción original no está definida en esos valores.`,
      t`La suma queda $(1/3-1/4)+(1/4-1/5)+\cdots+(1/102-1/103)=1/3-1/103=100/309$.`,
      t`Para $(7x-1)/(x^2-x-6)$, el planteamiento análogo da $7x-1=A(x+2)+B(x-3)$. Por coeficientes: $A+B=7$, $2A-3B=-1$. Evaluando en 3 y −2: $A=4$ y $B=3$.`,
      t`Por tanto, $(7x-1)/(x^2-x-6)=4/(x-3)+3/(x+2)$, con $x\ne3,-2$. Los factores repetidos requieren todas sus potencias; los cuadráticos irreducibles requieren numeradores lineales, como se desarrolla en el tema de fracciones parciales.`,
    ] },
  ],
};
