/** Adaptación de anotaciones revisadas visualmente; páginas físicas del PDF. */
export type HandwrittenNote = { title: string; pages: [number, number]; steps: string[]; correction?: string };
const t = String.raw;
export const handwrittenNotes: Record<string, HandwrittenNote[]> = {
  "ecuaciones-1": [
    { title: "Una solución algebraica puede estar prohibida", pages: [6, 7], steps: [t`En $\frac{2(2-x)}{x-1}+\frac{3-x}{x+1}+3=\frac4{x^2-1}$, primero excluimos $x=1$ y $x=-1$.`, t`Multiplicamos por $(x-1)(x+1)$: $2(2-x)(x+1)+(3-x)(x-1)+3(x^2-1)=4$.`, t`Al desarrollar se cancelan los términos cuadráticos y queda $6x-2=4$. La candidata $x=1$ no pertenece al dominio: el conjunto solución es vacío.`] },
  ],
  "ecuaciones-2": [
    { title: "La raíz de un cuadrado y el valor absoluto", pages: [16, 17], steps: [t`La raíz cuadrada principal nunca es negativa: $\sqrt{x^2}=|x|$, no necesariamente $x$. Con $x=-1$, la raíz vale $1$.`, t`Por eso, de $x^2=1$ obtenemos $|x|=1$ y las dos soluciones $x=\pm1$.`] },
    { title: "Separar casos y comprobar su intervalo", pages: [24, 27], steps: [t`Para $|3x-2|=4-x$, el cambio de expresión ocurre en $x=2/3$.`, t`Si $x\ge2/3$, resolvemos $3x-2=4-x$: $x=3/2$, que cumple la condición.`, t`Si $x<2/3$, resolvemos $-3x+2=4-x$: $x=-1$, que también cumple. Ambas candidatas satisfacen la ecuación original.`] },
    { title: "Dos valores absolutos: intersectar las condiciones", pages: [28, 42], steps: [t`En $|3x-2|=|2x+7|$ los cortes son $-7/2$ y $2/3$. Las condiciones de cada caso deben cumplirse simultáneamente; $x\ge2/3$ y $x<-7/2$ es un caso imposible.`, t`En $x<-7/2$ sale $x=9$, que se descarta. En $[-7/2,2/3)$ sale $x=-1$. En $[2/3,\infty)$ sale $x=9$.`, t`El procedimiento consiste en separar signos, escribir el intervalo permitido, resolver y comprobar pertenencia. Soluciones: $\{-1,9\}$.`] },
    { title: "Valores absolutos anidados", pages: [43, 45], steps: [t`Para $||x+1|-2|=1$, el interior del valor absoluto exterior puede valer $1$ o $-1$.`, t`Así, $|x+1|=3$ o $|x+1|=1$. Resolviendo ambas ecuaciones obtenemos $x\in\{-4,-2,0,2\}$.`] },
    { title: "Factorizar o usar la fórmula, conservando los signos", pages: [47, 55], steps: [t`En $x^2+5x-24$, buscamos dos números cuyo producto sea $-24$ y cuya suma sea $5$: $8$ y $-3$. Queda $(x+8)(x-3)$.`, t`En $3x^2-5x-1=0$, los coeficientes son $a=3$, $b=-5$, $c=-1$. El discriminante es $37$ y las raíces son $(5\pm\sqrt{37})/6$.`, t`Para $2x^2=-4x+6$, primero pasamos todo a un lado y dividimos por $2$: $x^2+2x-3=(x-1)(x+3)=0$. Las raíces son $1$ y $-3$.`] },
    { title: "Elegir un parámetro para tener raíz doble", pages: [59, 61], steps: [t`Una cuadrática tiene raíz doble cuando $\Delta=b^2-4ac=0$. Antes hay que verificar que el coeficiente cuadrático no sea cero.`, t`En $9x^2-kx+1=0$, $\Delta=k^2-36$, de modo que $k=\pm6$.`, t`En $3kx^2-2x+5=0$, $\Delta=4-60k$, así que $k=1/15$; este valor mantiene la ecuación cuadrática.`] },
  ],
  "ecuaciones-3": [
    { title: "Reconocer bases y elegir un cambio de variable", pages: [62, 70], steps: [t`$2^x=8=2^3$ da $x=3$; si $2^x=7$, escribimos $x=\log_2 7$. Un logaritmo expresa el exponente buscado.`, t`$3^x-4=23$ conduce a $3^x=27$ y $x=3$. En $5^{x-1}=0.04=5^{-2}$ obtenemos $x=-1$.`, t`En $e^{2x}-e^x-6=0$, hacemos $y=e^x>0$. Entonces $(y-3)(y+2)=0$; descartamos $y=-2$ y obtenemos $x=\ln3$.`] },
    { title: "En logaritmos, comprobar antes de aceptar raíces", pages: [73, 75], steps: [t`$\log_2(25-x)=3$ equivale a $25-x=8$, por lo que $x=17$ y el argumento es positivo.`, t`En $\log(x+2)+\log(x-1)=1$ (base $10$), necesitamos $x>1$. La ecuación $(x+2)(x-1)=10$ produce $3$ y $-4$, pero solo $3$ sirve.`, t`En $\log_5x+\log_5(x+1)=\log_5 20$, el dominio exige $x>0$. Las candidatas $4$ y $-5$ dejan únicamente $x=4$.`], correction: "En los dos últimos ejemplos, las raíces negativas no cumplen las condiciones del dominio y deben descartarse." },
    { title: "Reescribir potencias y recuperar la variable", pages: [76, 79], steps: [t`En $2^{x-1}+2^x=24$, tomamos $y=2^{x-1}$ y usamos $2^x=2y$. Sale $y=8$ y luego $x=4$.`, t`En $(2^x)^{x+1/2}=\sqrt8$, igualamos exponentes de base $2$: $x(x+1/2)=3/2$. Así $2x^2+x-3=0$, con $x=1$ o $x=-3/2$.`, t`En $2\log x=\log2+\log(3x-4)$, el dominio es $x>4/3$. La ecuación $x^2=2(3x-4)$ da $x=2$ y $x=4$, ambos admisibles.`] },
  ],
  "ecuaciones-4": [
    { title: "Traducir un reparto a una ecuación", pages: [12, 13], steps: [t`Si un total de $18000$ se reparte en cantidades $x$ y $18000-x$, no necesitamos dos incógnitas independientes.`, t`La ecuación que representa este reparto es $0.09x+0.06(18000-x)=1440$. Al reducir queda $0.03x=360$.`, t`Las cantidades son $12000$ y $6000$. Comprobamos que suman $18000$ y que $1080+360=1440$.`], correction: "Comprueba el resultado sustituyendo ambas cantidades en la ecuación del reparto." },
  ],
  "inecuaciones-2": [
    { title: "Estar dentro o fuera de una distancia", pages: [16, 19], steps: [t`$|2x-3|<5$ equivale a $-5<2x-3<5$, de donde $-1<x<4$.`, t`$|\frac35x-2|<1$ da $1<\frac35x<3$ y finalmente $5/3<x<5$.`, t`$|2-3x|>7$ exige $2-3x>7$ o $2-3x<-7$. Al dividir por $-3$ se invierte cada desigualdad: $x<-5/3$ o $x>3$.`] },
    { title: "Dos valores absolutos: corregir la tabla de signos", pages: [21, 24], steps: [t`En $|-2x+16|\ge|x+2|-1$, los cortes son $-2$ y $8$. El término $-2x+16$ es positivo a la izquierda de $8$.`, t`Si $x<-2$: $16-2x\ge-x-3$, que se cumple en todo ese intervalo. Si $-2\le x<8$: $16-2x\ge x+1$, y queda $[-2,5]$.`, t`Si $x\ge8$: $2x-16\ge x+1$, por lo que $x\ge17$. Uniendo casos: $(-\infty,5]\cup[17,\infty)$.`], correction: "Al separar los casos, recuerda que −2x+16 es positivo si x<8. Por ejemplo, x=0 satisface la desigualdad original." },
  ],
  "inecuaciones-3": [
    { title: "Leer los signos entre raíces", pages: [32, 38], steps: [t`Para $(x-2)(x-3)\le0$, las raíces dividen la recta en tres intervalos. Probando $0$, $5/2$ y $4$, los signos del producto son $+,-,+$. La solución es $[2,3]$.`, t`En $x^2>3(x+6)$ llevamos todo a la izquierda: $(x+3)(x-6)>0$. Buscamos los intervalos exteriores: $(-\infty,-3)\cup(6,\infty)$.`] },
    { title: "Una raíz doble no cambia el signo, pero sigue siendo cero", pages: [39, 40], steps: [t`En $x(x-1)^2(x-3)<0$, el factor $(x-1)^2$ es positivo salvo en $x=1$. Por eso no cambia el signo al atravesar esa raíz.`, t`El producto es negativo entre $0$ y $3$, excepto en $1$, donde vale cero. La solución correcta es $(0,1)\cup(1,3)$.`], correction: "No incluyas x=1: allí el producto vale cero y la desigualdad es estricta." },
    { title: "Conservar todos los cortes", pages: [50, 51], steps: [t`$18x-3x^2>0$ se factoriza como $3x(6-x)>0$, cuya solución es $(0,6)$.`, t`En $(x+3)(x-2)(x-4)<0$, los cortes son $-3,2,4$. Los signos sucesivos son $-,+,-,+$; elegimos $(-\infty,-3)\cup(2,4)$.`] },
  ],
  "inecuaciones-4": [
    { title: "No multiplicar por un denominador de signo desconocido", pages: [41, 48], steps: [t`Para $\frac{x}{x+2}\le x$, excluimos $-2$ y reunimos los términos: $\frac{x(x+1)}{x+2}\ge0$. Los cortes son $-2,-1,0$; resulta $(-2,-1]\cup[0,\infty)$.`, t`En $\frac x2\ge\frac5{x+1}+4$, excluimos $-1$. Al reunir términos obtenemos $\frac{(x+2)(x-9)}{2(x+1)}\ge0$.`, t`La solución es $[-2,-1)\cup[9,\infty)$. Los ceros del numerador pueden incluirse; los del denominador nunca.`] },
    { title: "Cambiar un signo afecta a toda la desigualdad", pages: [52, 53], steps: [t`$\frac{2x+1}{x+3}>3$ equivale a $\frac{-x-8}{x+3}>0$, con $x\ne-3$.`, t`Multiplicar por $-1$ da $\frac{x+8}{x+3}<0$. Numerador y denominador tienen signos opuestos en $(-8,-3)$.`] },
    { title: "Completar los casos de una fracción con valor absoluto", pages: [54, 55], steps: [t`En $|\frac{x-3}{5x}|<\frac13$, primero exigimos $x\ne0$. Como ambos lados son no negativos, podemos elevar al cuadrado.`, t`Resulta $9(x-3)^2<25x^2$, o $16x^2+54x-81>0$. Sus raíces son $-9/2$ y $9/8$.`, t`La solución completa es $(-\infty,-9/2)\cup(9/8,\infty)$.`], correction: "La solución debe considerar tanto x<0 como x>0, manteniendo x=0 fuera del dominio." },
  ],
  "funciones-1": [
    { title: "Leer cada elemento de la notación", pages: [2, 7], steps: [t`En $f:A\to B$, $f$ es el nombre; $A$ es el conjunto de partida y contiene a $x$; $B$ es el conjunto de llegada y contiene a $f(x)$. La regla asigna a cada entrada su imagen.`, t`Cada elemento de $A$ debe tener exactamente una imagen. Dos entradas pueden compartir imagen; una entrada sin imagen o con dos imágenes no cumple la definición.`, t`La gráfica contiene pares $(x,f(x))$. Una recta vertical no puede cortarla en dos puntos: por eso $y=x^2$ sí define una función de $x$, pero la circunferencia $x^2+y^2=4$ completa no.`] },
    { title: "El dominio se obtiene de las restricciones", pages: [8, 12], steps: [t`Para $\sqrt{x-2}$ necesitamos $x\ge2$. Para $1/(x^2-x)$, excluimos $0$ y $1$.`, t`En $\sqrt{9-x^2}$ exigimos $9-x^2\ge0$, de donde $x\in[-3,3]$. En $\log(x-2)$ la condición es estricta: $x>2$.`, t`No confundamos $\sqrt{x}-2$ con $\sqrt{x-2}$: una resta ocurre después de sacar la raíz y la otra dentro de ella.`] },
    { title: "Buscar qué valores puede tomar la imagen", pages: [13, 18], steps: [t`Para el recorrido, escribimos $y=f(x)$ y analizamos qué valores de $y$ son posibles. En $y=1/(x-2)$, despejar da $x=2+1/y$: se requiere $y\ne0$.`, t`$\sqrt{x-3}$ tiene recorrido $[0,\infty)$, mientras que $x^2-1$ tiene recorrido $[-1,\infty)$.`, t`Evaluar significa sustituir cada aparición de $x$. Si $f(x)=3x^2+x-5$, entonces $f(-2)=5$, $f(0)=-5$ y $f(a+3)=3(a+3)^2+(a+3)-5$. Los paréntesis conservan la entrada completa.`] },
  ],
  "funciones-2": [
    { title: "Pendiente, crecimiento y gráficas básicas", pages: [19, 29], steps: [t`Para estudiar crecimiento comparamos $f(x_1)$ y $f(x_2)$ cuando $x_1<x_2$. No se compara $x$ con $f(x)$.`, t`En una recta, $m=(y_2-y_1)/(x_2-x_1)$: pendiente positiva significa crecimiento; negativa, decrecimiento; cero, una función constante. Una recta vertical no es función de $x$.`, t`$f(x)=2x-1$ corta los ejes en $(0,-1)$ y $(1/2,0)$. $x^2$ decrece hasta $0$ y crece después; su recorrido es $[0,\infty)$. La raíz cuadrada crece en $[0,\infty)$.`] },
    { title: "Traslaciones y simetrías: mirar dónde ocurre el cambio", pages: [31, 34], steps: [t`$|x-2|$ desplaza la gráfica dos unidades a la derecha; $|x|+3$, tres hacia arriba; $|x-2|+3$ combina ambos cambios.`, t`$2-|x-1|$ tiene vértice en $(1,2)$ y abre hacia abajo. Además, $|1-x|=|x-1|$.`, t`Una función par satisface $f(-x)=f(x)$, como $x^2$ y $|x|$. Una impar satisface $f(-x)=-f(x)$, como $x$ y $x^3$.`] },
    { title: "Una función definida por el signo", pages: [35, 35], steps: [t`Separa el valor absoluto en casos para $f(x)=x/|x|$.`, t`Si $x>0$, vale $1$; si $x<0$, vale $-1$. En $x=0$ no está definida. Su recorrido es $\{-1,1\}$.`], correction: "El signo de x determina el valor de la función; x=0 queda fuera del dominio." },
  ],
  "funciones-3": [
    { title: "Seguir las restricciones a través de una transformación", pages: [42, 42], steps: [t`Para $f(x)=\sqrt{x-2}+5$, primero $x-2\ge0$, así que el dominio es $[2,\infty)$.`, t`Como la raíz es no negativa, $f(x)\ge5$; su recorrido es $[5,\infty)$. La función es creciente.`, t`No corta el eje vertical porque $0$ no está en su dominio, ni el horizontal porque nunca toma el valor $0$.`] },
  ],
  "trigonometria-1": [
    { title: "Operar valores exactos sin distribuir mal una raíz", pages: [19, 20], steps: [t`La raíz no se distribuye sobre una suma: $\sqrt2+\sqrt2=2\sqrt2$, mientras que $\sqrt{2+2}=2$. Conviene conservar las raíces hasta terminar el cálculo.`, t`En el ejemplo $\frac{\tan^2 30^\circ+\sin^2 30^\circ-\sin^2 45^\circ}{\tan^2 60^\circ+\cot^2 45^\circ-\cot^2 30^\circ+\cos^2 60^\circ}$, sustituimos los valores notables.`, t`El numerador vale $1/3+1/4-1/2=1/12$ y el denominador $3+1-3+1/4=5/4$. Dividir da $1/15$.`] },
    { title: "Ángulos y razones que no dependen del tamaño", pages: [2, 18], steps: [t`Los giros antihorarios se toman positivos y los horarios negativos. Una vuelta es $2\pi$ radianes: de grados a radianes multiplicamos por $\pi/180$. Así, $270^\circ=3\pi/2$ y $-5\pi/4=-225^\circ$.`, t`Los catetos opuesto y adyacente se nombran respecto del ángulo elegido. Triángulos semejantes de lados $3,4,5$ y $30,40,50$ dan la misma razón $4/5$.`, t`Los valores notables se construyen: partir un triángulo equilátero produce lados $1,\sqrt3,2$; la diagonal de un cuadrado produce $1,1,\sqrt2$. De ahí salen las razones de $30^\circ,60^\circ,45^\circ$.`] },
    { title: "Elegir la razón que usa los datos conocidos", pages: [22, 24], steps: [t`Para un faro de altura $90$ y ángulos de elevación de $60^\circ$ y $45^\circ$ desde puntos del mismo lado, usamos tangente: conocemos altura y buscamos distancias horizontales.`, t`Las distancias son $90/\sqrt3$ y $90$. Su separación es $90-30\sqrt3\approx38.04$.`, t`Si al avanzar $30$ hacia una torre el ángulo cambia de $30^\circ$ a $60^\circ$, planteamos $h/(x+30)=\tan30^\circ$ y $h/x=\tan60^\circ$. Se obtiene $x=15$ y $h=15\sqrt3$.`] },
  ],
  "trigonometria-2": [
    { title: "Signos, vueltas completas y ángulo de referencia", pages: [31, 51], steps: [t`En la circunferencia unitaria, el punto es $(\cos\theta,\sin\theta)$. Los signos se leen en sus coordenadas; no se pierden al usar un ángulo de referencia.`, t`$2\pi/3$ tiene referencia $\pi/3$ y está en el segundo cuadrante: coseno $-1/2$, seno $\sqrt3/2$, tangente $-\sqrt3$.`, t`Quitamos vueltas completas: $19\pi/4=4\pi+3\pi/4$ y $480^\circ=360^\circ+120^\circ$. Por eso $\cos480^\circ=-1/2$.`, t`La simetría da $\sin(-\theta)=-\sin\theta$, $\cos(-\theta)=\cos\theta$ y $\tan(-\theta)=-\tan\theta$.`], correction: "El seno es una función impar: en particular, sin(−π/6)=−1/2." },
  ],
  "trigonometria-3": [
    { title: "Construir identidades y respetar sus denominadores", pages: [25, 30], steps: [t`De $\sin^2\theta+\cos^2\theta=1$, dividir por $\cos^2\theta$ da $1+\tan^2\theta=\sec^2\theta$ donde $\cos\theta\ne0$. Dividir por $\sin^2\theta$ da $1+\cot^2\theta=\csc^2\theta$ donde $\sin\theta\ne0$.`, t`En $\frac{\csc\theta}{1+\csc\theta}-\frac1{\sin\theta-1}$, sustituir $s=\sin\theta$ da $\frac1{1+s}-\frac1{s-1}=\frac2{1-s^2}=2\sec^2\theta$.`, t`La igualdad vale en el dominio original: $\sin\theta\ne0$ y $\cos\theta\ne0$. Simplificar una expresión no recupera puntos antes prohibidos.`] },
    { title: "Elegir una identidad que simplifique el cálculo", pages: [52, 59], steps: [t`La fórmula de la diferencia se obtiene de la suma sustituyendo un ángulo negativo y usando la paridad. Por ejemplo, $\sin(a-b)=\sin a\cos b-\cos a\sin b$.`, t`$\cos75^\circ=\cos(45^\circ+30^\circ)=(\sqrt6-\sqrt2)/4$. También $\sin20^\circ\cos40^\circ+\cos20^\circ\sin40^\circ=\sin60^\circ=\sqrt3/2$.`, t`Para ángulo doble: $\sin2a=2\sin a\cos a$ y $\cos2a=1-2\sin^2a=2\cos^2a-1$. Elegimos la forma según la función que queremos eliminar.`], correction: "Para el seno de un ángulo doble, usa sin(2a)=2 sin(a) cos(a)." },
    { title: "Leer amplitud, período y desplazamientos", pages: [88, 103], steps: [t`La circunferencia extiende el seno a todo $\mathbb R$. Su recorrido es $[-1,1]$, sus ceros son $k\pi$ y su período es $2\pi$.`, t`Para $A\sin(Bx+C)+D$, con $A\ne0$ y $B\ne0$, la amplitud es $|A|$, el período $2\pi/|B|$, el recorrido $[D-|A|,D+|A|]$ y el desplazamiento horizontal $-C/B$.`, t`En $2\sin(3x)-1$, amplitud $2$, período $2\pi/3$ y recorrido $[-3,1]$. En $-3\sin(2x-\pi/2)+1$, reescribimos el argumento como $2(x-\pi/4)$: desplazamiento $\pi/4$ a la derecha, período $\pi$, amplitud $3$ y recorrido $[-2,4]$.`], correction: "La amplitud depende de |A|; si A es negativo, la gráfica también se refleja verticalmente. El período se calcula con |B|, incluso cuando B es negativo." },
  ],
  "trigonometria-4": [
    { title: "La inversa entrega un valor principal, no todos los ángulos", pages: [65, 72], steps: [t`$\arcsin$ toma valores en $[-\pi/2,\pi/2]$. Por eso $\arcsin(\sin(2\pi/3))=\pi/3$.`, t`$\arccos$ toma valores en $[0,\pi]$. Así, $\arccos(\cos(5\pi/3))=\pi/3$, mientras que $\arccos(\cos(2\pi/3))=2\pi/3$.`, t`Resolver $\cos\theta=1/2$ requiere las dos familias: $\theta=\pi/3+2k\pi$ o $5\pi/3+2k\pi$, con $k\in\mathbb Z$.`], correction: "El recorrido de arccos es [0,π]; verifica que el resultado pertenezca a ese intervalo." },
    { title: "Un cambio de variable también tiene restricciones", pages: [75, 75], steps: [t`En $2\cos^2\theta-7\cos\theta+3=0$, tomamos $u=\cos\theta$. La cuadrática da $u=1/2$ o $u=3$.`, t`Descartamos $u=3$ porque el coseno está entre $-1$ y $1$. Quedan $\theta=\pi/3+2k\pi$ o $5\pi/3+2k\pi$, $k\in\mathbb Z$.`] },
    { title: "Factorizar sin perder las soluciones de un factor", pages: [76, 79], steps: [t`$5\sin\theta\cos\theta+4\cos\theta=0$ se escribe $\cos\theta(5\sin\theta+4)=0$. No dividimos por el coseno: perderíamos sus ceros.`, t`Una familia es $\theta=\pi/2+k\pi$. Para la otra, sea $a=\arcsin(4/5)$: $\theta=-a+2k\pi$ o $\pi+a+2k\pi$.`, t`De forma similar, $\sin2\theta=\cos\theta$ lleva a $\cos\theta(2\sin\theta-1)=0$. Se unen $\pi/2+k\pi$, $\pi/6+2k\pi$ y $5\pi/6+2k\pi$, con $k\in\mathbb Z$.`] },
    { title: "Dividir también el período y filtrar por intervalo", pages: [73, 85], steps: [t`$2\sin(3\theta)-1=0$ implica $3\theta=\pi/6+2k\pi$ o $5\pi/6+2k\pi$. Al dividir todo por $3$: $\theta=\pi/18+2k\pi/3$ o $5\pi/18+2k\pi/3$.`, t`En $[0,2\pi)$ usamos $k=0,1,2$ en ambas familias: $\pi/18,5\pi/18,13\pi/18,17\pi/18,25\pi/18,29\pi/18$.`, t`En $\cos2x=\sin x+1$, conviene $\cos2x=1-2\sin^2x$. Queda $\sin x(2\sin x+1)=0$: $x=k\pi$, $7\pi/6+2k\pi$ o $11\pi/6+2k\pi$.`] },
  ],
  "trigonometria-5": [
    { title: "Relacionar cada lado con su ángulo opuesto", pages: [110, 112], steps: [t`El teorema del seno no requiere un triángulo rectángulo. Cada razón debe emparejar un lado con el seno de su ángulo opuesto.`, t`En el ejemplo de las estaciones separadas $340$ millas, los ángulos son $60^\circ$, $75^\circ$ y $45^\circ$. La distancia $p$ al satélite desde Los Ángeles es opuesta a $60^\circ$.`, t`$p/\sin60^\circ=340/\sin45^\circ$, de donde $p=170\sqrt6\approx416.41$ millas.`] },
    { title: "Tres lados conocidos: despejar los cosenos", pages: [113, 117], steps: [t`Con $a=5$, $b=8$, $c=12$, el teorema del coseno da $\cos\alpha=(b^2+c^2-a^2)/(2bc)=183/192$.`, t`De igual modo, $\cos\beta=105/120$ y $\cos\gamma=-55/80$. Aplicamos arccos y convertimos a grados.`, t`Sin redondear antes de tiempo: $\alpha\approx17.61^\circ$, $\beta\approx28.96^\circ$, $\gamma\approx133.43^\circ$. La suma es $180^\circ$.`], correction: "Conserva las fracciones hasta el cálculo final: redondear 183/192 a 0.95 altera α. Además, arccos(0.875) es aproximadamente 28.96°." },
  ],
  "vectores-1": [
    { title: "Un vector es un desplazamiento, no su punto de partida", pages: [2, 11], steps: [t`Magnitud es el tamaño, dirección la orientación de la recta y sentido hacia dónde apunta la flecha. Las componentes se calculan como final menos inicial.`, t`De $P=(-1,6)$ a $Q=(4,8)$: $\overrightarrow{PQ}=(5,2)$. Si conocemos el vector $(3,7)$ y el inicio $(3,5)$, el final es $(6,12)$.`, t`El mismo vector $(3,5)$ puede comenzar en $(0,0)$, $(2,3)$ o $(-3,5)$; termina en $(3,5)$, $(5,8)$ o $(0,10)$.`, t`La norma se calcula con los cuadrados: $\|(-2,3)\|=\sqrt{13}$, $\|(1,-1)\|=\sqrt2$ y $\|(-3,0)\|=3$.`] },
  ],
  "vectores-2": [
    { title: "Operar componente a componente", pages: [12, 16], steps: [t`Con $u=(2,-3)$ y $v=(-1,2)$, $u+v=(1,-1)$ y $u-v=(3,-5)$. Restar afecta a todas las componentes de $v$.`, t`$2u=(4,-6)$, $-3v=(3,-6)$ y $2u+3v=(1,0)$.`, t`La norma de un múltiplo cumple $\|cu\|=|c|\|u\|$: al sacar la raíz de $c^2$ aparece $|c|$, pues una longitud no es negativa.`] },
    { title: "Normalizar y escribir en la base estándar", pages: [17, 23], steps: [t`El vector $(3/5,4/5)$ es unitario porque la suma de sus componentes al cuadrado es $1$.`, t`Para normalizar $(2,-1)$, dividimos por $\sqrt5$: $(2/\sqrt5,-1/\sqrt5)$. Su opuesto también es unitario, pero tiene sentido contrario. Nunca se normaliza el vector cero.`, t`Con $u=3i+j$ y $v=5i-2j$, $4u-2v=(12-10)i+(4+4)j=2i+8j$.`] },
  ],
  "vectores-3": [
    { title: "Producto punto: un número que informa sobre el ángulo", pages: [29, 36], steps: [t`El resultado es escalar: $(3,-2)\cdot(4,5)=12-10=2$. Además, $u\cdot u=\|u\|^2$.`, t`Para $u=(2,5)$ y $v=(4,-3)$, $u\cdot v=-7$ y $\cos\theta=-7/(5\sqrt{29})$. El ángulo es obtuso, aproximadamente $105.1^\circ$.`, t`$(2,1)\cdot(-1,2)=0$, así que son perpendiculares. Si $(2,4)$ debe ser perpendicular a $(n,1)$, resolvemos $2n+4=0$: $n=-2$.`] },
  ],
  "vectores-4": [
    { title: "El ángulo necesita el cuadrante", pages: [24, 28], steps: [t`Para $u=(-\sqrt3,1)$, la primera componente es negativa y la segunda positiva: está en el segundo cuadrante.`, t`Aunque $\arctan(-1/\sqrt3)=-\pi/6$, ese valor principal no da la dirección buscada. El ángulo desde el eje horizontal positivo es $5\pi/6$.`] },
    { title: "En tres dimensiones se conserva final menos inicial", pages: [37, 45], steps: [t`El orden de las coordenadas es $(x,y,z)$. Para $P=(2,-1,7)$ y $Q=(1,-3,5)$, la distancia es $\sqrt{(-1)^2+(-2)^2+(-2)^2}=3$.`, t`De $P=(1,-4,5)$ a $Q=(3,1,-1)$, el vector es $(2,5,-6)$.`, t`Si el inicio es $(2,1,-1)$ y el desplazamiento $(-2,1,3)$, el punto final es $(0,2,2)$.`], correction: "Para hallar el punto final, suma el vector de desplazamiento al punto inicial." },
    { title: "Producto punto y cosenos directores en el espacio", pages: [49, 55], steps: [t`En tres dimensiones también sumamos los productos de componentes: $(-1,2,3)\cdot(6,5,-1)=1$. Los vectores $(2,2,-1)$ y $(5,-4,2)$ son perpendiculares porque su producto punto es $0$.`, t`Para un vector no nulo $v=(a,b,c)$, las componentes de $v/\|v\|$ son los cosenos de sus ángulos con los ejes: $(\cos\alpha,\cos\beta,\cos\gamma)$.`, t`Como el vector normalizado tiene norma $1$, se cumple $\cos^2\alpha+\cos^2\beta+\cos^2\gamma=1$.`] },
  ],
};
export const handwrittenNoteCount = Object.values(handwrittenNotes).reduce((total, notes) => total + notes.length, 0);
